#include <node.h>

// Includes
#include "gl.h"
#include <GL/gl.h>
#include <GL/glext.h>

using namespace v8;
namespace node {

  void gl::Initialize(v8::Handle<v8::Object> target) {
    HandleScope scope;

    // Constants
    #ifdef GL_VERSION_1_1
NODE_DEFINE_CONSTANT(target, GL_VERSION_1_1);
#endif

    #ifdef GL_VERSION_1_2
NODE_DEFINE_CONSTANT(target, GL_VERSION_1_2);
#endif

    #ifdef GL_VERSION_1_3
NODE_DEFINE_CONSTANT(target, GL_VERSION_1_3);
#endif

    #ifdef GL_ARB_imaging
NODE_DEFINE_CONSTANT(target, GL_ARB_imaging);
#endif

    #ifdef GL_FALSE
NODE_DEFINE_CONSTANT(target, GL_FALSE);
#endif

    #ifdef GL_TRUE
NODE_DEFINE_CONSTANT(target, GL_TRUE);
#endif

    #ifdef GL_BYTE
NODE_DEFINE_CONSTANT(target, GL_BYTE);
#endif

    #ifdef GL_UNSIGNED_BYTE
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_BYTE);
#endif

    #ifdef GL_SHORT
NODE_DEFINE_CONSTANT(target, GL_SHORT);
#endif

    #ifdef GL_UNSIGNED_SHORT
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT);
#endif

    #ifdef GL_INT
NODE_DEFINE_CONSTANT(target, GL_INT);
#endif

    #ifdef GL_UNSIGNED_INT
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_INT);
#endif

    #ifdef GL_FLOAT
NODE_DEFINE_CONSTANT(target, GL_FLOAT);
#endif

    #ifdef GL_2_BYTES
NODE_DEFINE_CONSTANT(target, GL_2_BYTES);
#endif

    #ifdef GL_3_BYTES
NODE_DEFINE_CONSTANT(target, GL_3_BYTES);
#endif

    #ifdef GL_4_BYTES
NODE_DEFINE_CONSTANT(target, GL_4_BYTES);
#endif

    #ifdef GL_DOUBLE
NODE_DEFINE_CONSTANT(target, GL_DOUBLE);
#endif

    #ifdef GL_POINTS
NODE_DEFINE_CONSTANT(target, GL_POINTS);
#endif

    #ifdef GL_LINES
NODE_DEFINE_CONSTANT(target, GL_LINES);
#endif

    #ifdef GL_LINE_LOOP
NODE_DEFINE_CONSTANT(target, GL_LINE_LOOP);
#endif

    #ifdef GL_LINE_STRIP
NODE_DEFINE_CONSTANT(target, GL_LINE_STRIP);
#endif

    #ifdef GL_TRIANGLES
NODE_DEFINE_CONSTANT(target, GL_TRIANGLES);
#endif

    #ifdef GL_TRIANGLE_STRIP
NODE_DEFINE_CONSTANT(target, GL_TRIANGLE_STRIP);
#endif

    #ifdef GL_TRIANGLE_FAN
NODE_DEFINE_CONSTANT(target, GL_TRIANGLE_FAN);
#endif

    #ifdef GL_QUADS
NODE_DEFINE_CONSTANT(target, GL_QUADS);
#endif

    #ifdef GL_QUAD_STRIP
NODE_DEFINE_CONSTANT(target, GL_QUAD_STRIP);
#endif

    #ifdef GL_POLYGON
NODE_DEFINE_CONSTANT(target, GL_POLYGON);
#endif

    #ifdef GL_VERTEX_ARRAY
NODE_DEFINE_CONSTANT(target, GL_VERTEX_ARRAY);
#endif

    #ifdef GL_NORMAL_ARRAY
NODE_DEFINE_CONSTANT(target, GL_NORMAL_ARRAY);
#endif

    #ifdef GL_COLOR_ARRAY
NODE_DEFINE_CONSTANT(target, GL_COLOR_ARRAY);
#endif

    #ifdef GL_INDEX_ARRAY
NODE_DEFINE_CONSTANT(target, GL_INDEX_ARRAY);
#endif

    #ifdef GL_TEXTURE_COORD_ARRAY
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COORD_ARRAY);
#endif

    #ifdef GL_EDGE_FLAG_ARRAY
NODE_DEFINE_CONSTANT(target, GL_EDGE_FLAG_ARRAY);
#endif

    #ifdef GL_VERTEX_ARRAY_SIZE
NODE_DEFINE_CONSTANT(target, GL_VERTEX_ARRAY_SIZE);
#endif

    #ifdef GL_VERTEX_ARRAY_TYPE
NODE_DEFINE_CONSTANT(target, GL_VERTEX_ARRAY_TYPE);
#endif

    #ifdef GL_VERTEX_ARRAY_STRIDE
NODE_DEFINE_CONSTANT(target, GL_VERTEX_ARRAY_STRIDE);
#endif

    #ifdef GL_NORMAL_ARRAY_TYPE
NODE_DEFINE_CONSTANT(target, GL_NORMAL_ARRAY_TYPE);
#endif

    #ifdef GL_NORMAL_ARRAY_STRIDE
NODE_DEFINE_CONSTANT(target, GL_NORMAL_ARRAY_STRIDE);
#endif

    #ifdef GL_COLOR_ARRAY_SIZE
NODE_DEFINE_CONSTANT(target, GL_COLOR_ARRAY_SIZE);
#endif

    #ifdef GL_COLOR_ARRAY_TYPE
NODE_DEFINE_CONSTANT(target, GL_COLOR_ARRAY_TYPE);
#endif

    #ifdef GL_COLOR_ARRAY_STRIDE
NODE_DEFINE_CONSTANT(target, GL_COLOR_ARRAY_STRIDE);
#endif

    #ifdef GL_INDEX_ARRAY_TYPE
NODE_DEFINE_CONSTANT(target, GL_INDEX_ARRAY_TYPE);
#endif

    #ifdef GL_INDEX_ARRAY_STRIDE
NODE_DEFINE_CONSTANT(target, GL_INDEX_ARRAY_STRIDE);
#endif

    #ifdef GL_TEXTURE_COORD_ARRAY_SIZE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COORD_ARRAY_SIZE);
#endif

    #ifdef GL_TEXTURE_COORD_ARRAY_TYPE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COORD_ARRAY_TYPE);
#endif

    #ifdef GL_TEXTURE_COORD_ARRAY_STRIDE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COORD_ARRAY_STRIDE);
#endif

    #ifdef GL_EDGE_FLAG_ARRAY_STRIDE
NODE_DEFINE_CONSTANT(target, GL_EDGE_FLAG_ARRAY_STRIDE);
#endif

    #ifdef GL_VERTEX_ARRAY_POINTER
NODE_DEFINE_CONSTANT(target, GL_VERTEX_ARRAY_POINTER);
#endif

    #ifdef GL_NORMAL_ARRAY_POINTER
NODE_DEFINE_CONSTANT(target, GL_NORMAL_ARRAY_POINTER);
#endif

    #ifdef GL_COLOR_ARRAY_POINTER
NODE_DEFINE_CONSTANT(target, GL_COLOR_ARRAY_POINTER);
#endif

    #ifdef GL_INDEX_ARRAY_POINTER
NODE_DEFINE_CONSTANT(target, GL_INDEX_ARRAY_POINTER);
#endif

    #ifdef GL_TEXTURE_COORD_ARRAY_POINTER
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COORD_ARRAY_POINTER);
#endif

    #ifdef GL_EDGE_FLAG_ARRAY_POINTER
NODE_DEFINE_CONSTANT(target, GL_EDGE_FLAG_ARRAY_POINTER);
#endif

    #ifdef GL_V2F
NODE_DEFINE_CONSTANT(target, GL_V2F);
#endif

    #ifdef GL_V3F
NODE_DEFINE_CONSTANT(target, GL_V3F);
#endif

    #ifdef GL_C4UB_V2F
NODE_DEFINE_CONSTANT(target, GL_C4UB_V2F);
#endif

    #ifdef GL_C4UB_V3F
NODE_DEFINE_CONSTANT(target, GL_C4UB_V3F);
#endif

    #ifdef GL_C3F_V3F
NODE_DEFINE_CONSTANT(target, GL_C3F_V3F);
#endif

    #ifdef GL_N3F_V3F
NODE_DEFINE_CONSTANT(target, GL_N3F_V3F);
#endif

    #ifdef GL_C4F_N3F_V3F
NODE_DEFINE_CONSTANT(target, GL_C4F_N3F_V3F);
#endif

    #ifdef GL_T2F_V3F
NODE_DEFINE_CONSTANT(target, GL_T2F_V3F);
#endif

    #ifdef GL_T4F_V4F
NODE_DEFINE_CONSTANT(target, GL_T4F_V4F);
#endif

    #ifdef GL_T2F_C4UB_V3F
NODE_DEFINE_CONSTANT(target, GL_T2F_C4UB_V3F);
#endif

    #ifdef GL_T2F_C3F_V3F
NODE_DEFINE_CONSTANT(target, GL_T2F_C3F_V3F);
#endif

    #ifdef GL_T2F_N3F_V3F
NODE_DEFINE_CONSTANT(target, GL_T2F_N3F_V3F);
#endif

    #ifdef GL_T2F_C4F_N3F_V3F
NODE_DEFINE_CONSTANT(target, GL_T2F_C4F_N3F_V3F);
#endif

    #ifdef GL_T4F_C4F_N3F_V4F
NODE_DEFINE_CONSTANT(target, GL_T4F_C4F_N3F_V4F);
#endif

    #ifdef GL_MATRIX_MODE
NODE_DEFINE_CONSTANT(target, GL_MATRIX_MODE);
#endif

    #ifdef GL_MODELVIEW
NODE_DEFINE_CONSTANT(target, GL_MODELVIEW);
#endif

    #ifdef GL_PROJECTION
NODE_DEFINE_CONSTANT(target, GL_PROJECTION);
#endif

    #ifdef GL_TEXTURE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE);
#endif

    #ifdef GL_POINT_SMOOTH
NODE_DEFINE_CONSTANT(target, GL_POINT_SMOOTH);
#endif

    #ifdef GL_POINT_SIZE
NODE_DEFINE_CONSTANT(target, GL_POINT_SIZE);
#endif

    #ifdef GL_POINT_SIZE_GRANULARITY
NODE_DEFINE_CONSTANT(target, GL_POINT_SIZE_GRANULARITY);
#endif

    #ifdef GL_POINT_SIZE_RANGE
NODE_DEFINE_CONSTANT(target, GL_POINT_SIZE_RANGE);
#endif

    #ifdef GL_LINE_SMOOTH
NODE_DEFINE_CONSTANT(target, GL_LINE_SMOOTH);
#endif

    #ifdef GL_LINE_STIPPLE
NODE_DEFINE_CONSTANT(target, GL_LINE_STIPPLE);
#endif

    #ifdef GL_LINE_STIPPLE_PATTERN
NODE_DEFINE_CONSTANT(target, GL_LINE_STIPPLE_PATTERN);
#endif

    #ifdef GL_LINE_STIPPLE_REPEAT
NODE_DEFINE_CONSTANT(target, GL_LINE_STIPPLE_REPEAT);
#endif

    #ifdef GL_LINE_WIDTH
NODE_DEFINE_CONSTANT(target, GL_LINE_WIDTH);
#endif

    #ifdef GL_LINE_WIDTH_GRANULARITY
NODE_DEFINE_CONSTANT(target, GL_LINE_WIDTH_GRANULARITY);
#endif

    #ifdef GL_LINE_WIDTH_RANGE
NODE_DEFINE_CONSTANT(target, GL_LINE_WIDTH_RANGE);
#endif

    #ifdef GL_POINT
NODE_DEFINE_CONSTANT(target, GL_POINT);
#endif

    #ifdef GL_LINE
NODE_DEFINE_CONSTANT(target, GL_LINE);
#endif

    #ifdef GL_FILL
NODE_DEFINE_CONSTANT(target, GL_FILL);
#endif

    #ifdef GL_CW
NODE_DEFINE_CONSTANT(target, GL_CW);
#endif

    #ifdef GL_CCW
NODE_DEFINE_CONSTANT(target, GL_CCW);
#endif

    #ifdef GL_FRONT
NODE_DEFINE_CONSTANT(target, GL_FRONT);
#endif

    #ifdef GL_BACK
NODE_DEFINE_CONSTANT(target, GL_BACK);
#endif

    #ifdef GL_POLYGON_MODE
NODE_DEFINE_CONSTANT(target, GL_POLYGON_MODE);
#endif

    #ifdef GL_POLYGON_SMOOTH
NODE_DEFINE_CONSTANT(target, GL_POLYGON_SMOOTH);
#endif

    #ifdef GL_POLYGON_STIPPLE
NODE_DEFINE_CONSTANT(target, GL_POLYGON_STIPPLE);
#endif

    #ifdef GL_EDGE_FLAG
NODE_DEFINE_CONSTANT(target, GL_EDGE_FLAG);
#endif

    #ifdef GL_CULL_FACE
NODE_DEFINE_CONSTANT(target, GL_CULL_FACE);
#endif

    #ifdef GL_CULL_FACE_MODE
NODE_DEFINE_CONSTANT(target, GL_CULL_FACE_MODE);
#endif

    #ifdef GL_FRONT_FACE
NODE_DEFINE_CONSTANT(target, GL_FRONT_FACE);
#endif

    #ifdef GL_POLYGON_OFFSET_FACTOR
NODE_DEFINE_CONSTANT(target, GL_POLYGON_OFFSET_FACTOR);
#endif

    #ifdef GL_POLYGON_OFFSET_UNITS
NODE_DEFINE_CONSTANT(target, GL_POLYGON_OFFSET_UNITS);
#endif

    #ifdef GL_POLYGON_OFFSET_POINT
NODE_DEFINE_CONSTANT(target, GL_POLYGON_OFFSET_POINT);
#endif

    #ifdef GL_POLYGON_OFFSET_LINE
NODE_DEFINE_CONSTANT(target, GL_POLYGON_OFFSET_LINE);
#endif

    #ifdef GL_POLYGON_OFFSET_FILL
NODE_DEFINE_CONSTANT(target, GL_POLYGON_OFFSET_FILL);
#endif

    #ifdef GL_COMPILE
NODE_DEFINE_CONSTANT(target, GL_COMPILE);
#endif

    #ifdef GL_COMPILE_AND_EXECUTE
NODE_DEFINE_CONSTANT(target, GL_COMPILE_AND_EXECUTE);
#endif

    #ifdef GL_LIST_BASE
NODE_DEFINE_CONSTANT(target, GL_LIST_BASE);
#endif

    #ifdef GL_LIST_INDEX
NODE_DEFINE_CONSTANT(target, GL_LIST_INDEX);
#endif

    #ifdef GL_LIST_MODE
NODE_DEFINE_CONSTANT(target, GL_LIST_MODE);
#endif

    #ifdef GL_NEVER
NODE_DEFINE_CONSTANT(target, GL_NEVER);
#endif

    #ifdef GL_LESS
NODE_DEFINE_CONSTANT(target, GL_LESS);
#endif

    #ifdef GL_EQUAL
NODE_DEFINE_CONSTANT(target, GL_EQUAL);
#endif

    #ifdef GL_LEQUAL
NODE_DEFINE_CONSTANT(target, GL_LEQUAL);
#endif

    #ifdef GL_GREATER
NODE_DEFINE_CONSTANT(target, GL_GREATER);
#endif

    #ifdef GL_NOTEQUAL
NODE_DEFINE_CONSTANT(target, GL_NOTEQUAL);
#endif

    #ifdef GL_GEQUAL
NODE_DEFINE_CONSTANT(target, GL_GEQUAL);
#endif

    #ifdef GL_ALWAYS
NODE_DEFINE_CONSTANT(target, GL_ALWAYS);
#endif

    #ifdef GL_DEPTH_TEST
NODE_DEFINE_CONSTANT(target, GL_DEPTH_TEST);
#endif

    #ifdef GL_DEPTH_BITS
NODE_DEFINE_CONSTANT(target, GL_DEPTH_BITS);
#endif

    #ifdef GL_DEPTH_CLEAR_VALUE
NODE_DEFINE_CONSTANT(target, GL_DEPTH_CLEAR_VALUE);
#endif

    #ifdef GL_DEPTH_FUNC
NODE_DEFINE_CONSTANT(target, GL_DEPTH_FUNC);
#endif

    #ifdef GL_DEPTH_RANGE
NODE_DEFINE_CONSTANT(target, GL_DEPTH_RANGE);
#endif

    #ifdef GL_DEPTH_WRITEMASK
NODE_DEFINE_CONSTANT(target, GL_DEPTH_WRITEMASK);
#endif

    #ifdef GL_DEPTH_COMPONENT
NODE_DEFINE_CONSTANT(target, GL_DEPTH_COMPONENT);
#endif

    #ifdef GL_LIGHTING
NODE_DEFINE_CONSTANT(target, GL_LIGHTING);
#endif

    #ifdef GL_LIGHT0
NODE_DEFINE_CONSTANT(target, GL_LIGHT0);
#endif

    #ifdef GL_LIGHT1
NODE_DEFINE_CONSTANT(target, GL_LIGHT1);
#endif

    #ifdef GL_LIGHT2
NODE_DEFINE_CONSTANT(target, GL_LIGHT2);
#endif

    #ifdef GL_LIGHT3
NODE_DEFINE_CONSTANT(target, GL_LIGHT3);
#endif

    #ifdef GL_LIGHT4
NODE_DEFINE_CONSTANT(target, GL_LIGHT4);
#endif

    #ifdef GL_LIGHT5
NODE_DEFINE_CONSTANT(target, GL_LIGHT5);
#endif

    #ifdef GL_LIGHT6
NODE_DEFINE_CONSTANT(target, GL_LIGHT6);
#endif

    #ifdef GL_LIGHT7
NODE_DEFINE_CONSTANT(target, GL_LIGHT7);
#endif

    #ifdef GL_SPOT_EXPONENT
NODE_DEFINE_CONSTANT(target, GL_SPOT_EXPONENT);
#endif

    #ifdef GL_SPOT_CUTOFF
NODE_DEFINE_CONSTANT(target, GL_SPOT_CUTOFF);
#endif

    #ifdef GL_CONSTANT_ATTENUATION
NODE_DEFINE_CONSTANT(target, GL_CONSTANT_ATTENUATION);
#endif

    #ifdef GL_LINEAR_ATTENUATION
NODE_DEFINE_CONSTANT(target, GL_LINEAR_ATTENUATION);
#endif

    #ifdef GL_QUADRATIC_ATTENUATION
NODE_DEFINE_CONSTANT(target, GL_QUADRATIC_ATTENUATION);
#endif

    #ifdef GL_AMBIENT
NODE_DEFINE_CONSTANT(target, GL_AMBIENT);
#endif

    #ifdef GL_DIFFUSE
NODE_DEFINE_CONSTANT(target, GL_DIFFUSE);
#endif

    #ifdef GL_SPECULAR
NODE_DEFINE_CONSTANT(target, GL_SPECULAR);
#endif

    #ifdef GL_SHININESS
NODE_DEFINE_CONSTANT(target, GL_SHININESS);
#endif

    #ifdef GL_EMISSION
NODE_DEFINE_CONSTANT(target, GL_EMISSION);
#endif

    #ifdef GL_POSITION
NODE_DEFINE_CONSTANT(target, GL_POSITION);
#endif

    #ifdef GL_SPOT_DIRECTION
NODE_DEFINE_CONSTANT(target, GL_SPOT_DIRECTION);
#endif

    #ifdef GL_AMBIENT_AND_DIFFUSE
NODE_DEFINE_CONSTANT(target, GL_AMBIENT_AND_DIFFUSE);
#endif

    #ifdef GL_COLOR_INDEXES
NODE_DEFINE_CONSTANT(target, GL_COLOR_INDEXES);
#endif

    #ifdef GL_LIGHT_MODEL_TWO_SIDE
NODE_DEFINE_CONSTANT(target, GL_LIGHT_MODEL_TWO_SIDE);
#endif

    #ifdef GL_LIGHT_MODEL_LOCAL_VIEWER
NODE_DEFINE_CONSTANT(target, GL_LIGHT_MODEL_LOCAL_VIEWER);
#endif

    #ifdef GL_LIGHT_MODEL_AMBIENT
NODE_DEFINE_CONSTANT(target, GL_LIGHT_MODEL_AMBIENT);
#endif

    #ifdef GL_FRONT_AND_BACK
NODE_DEFINE_CONSTANT(target, GL_FRONT_AND_BACK);
#endif

    #ifdef GL_SHADE_MODEL
NODE_DEFINE_CONSTANT(target, GL_SHADE_MODEL);
#endif

    #ifdef GL_FLAT
NODE_DEFINE_CONSTANT(target, GL_FLAT);
#endif

    #ifdef GL_SMOOTH
NODE_DEFINE_CONSTANT(target, GL_SMOOTH);
#endif

    #ifdef GL_COLOR_MATERIAL
NODE_DEFINE_CONSTANT(target, GL_COLOR_MATERIAL);
#endif

    #ifdef GL_COLOR_MATERIAL_FACE
NODE_DEFINE_CONSTANT(target, GL_COLOR_MATERIAL_FACE);
#endif

    #ifdef GL_COLOR_MATERIAL_PARAMETER
NODE_DEFINE_CONSTANT(target, GL_COLOR_MATERIAL_PARAMETER);
#endif

    #ifdef GL_NORMALIZE
NODE_DEFINE_CONSTANT(target, GL_NORMALIZE);
#endif

    #ifdef GL_CLIP_PLANE0
NODE_DEFINE_CONSTANT(target, GL_CLIP_PLANE0);
#endif

    #ifdef GL_CLIP_PLANE1
NODE_DEFINE_CONSTANT(target, GL_CLIP_PLANE1);
#endif

    #ifdef GL_CLIP_PLANE2
NODE_DEFINE_CONSTANT(target, GL_CLIP_PLANE2);
#endif

    #ifdef GL_CLIP_PLANE3
NODE_DEFINE_CONSTANT(target, GL_CLIP_PLANE3);
#endif

    #ifdef GL_CLIP_PLANE4
NODE_DEFINE_CONSTANT(target, GL_CLIP_PLANE4);
#endif

    #ifdef GL_CLIP_PLANE5
NODE_DEFINE_CONSTANT(target, GL_CLIP_PLANE5);
#endif

    #ifdef GL_ACCUM_RED_BITS
NODE_DEFINE_CONSTANT(target, GL_ACCUM_RED_BITS);
#endif

    #ifdef GL_ACCUM_GREEN_BITS
NODE_DEFINE_CONSTANT(target, GL_ACCUM_GREEN_BITS);
#endif

    #ifdef GL_ACCUM_BLUE_BITS
NODE_DEFINE_CONSTANT(target, GL_ACCUM_BLUE_BITS);
#endif

    #ifdef GL_ACCUM_ALPHA_BITS
NODE_DEFINE_CONSTANT(target, GL_ACCUM_ALPHA_BITS);
#endif

    #ifdef GL_ACCUM_CLEAR_VALUE
NODE_DEFINE_CONSTANT(target, GL_ACCUM_CLEAR_VALUE);
#endif

    #ifdef GL_ACCUM
NODE_DEFINE_CONSTANT(target, GL_ACCUM);
#endif

    #ifdef GL_ADD
NODE_DEFINE_CONSTANT(target, GL_ADD);
#endif

    #ifdef GL_LOAD
NODE_DEFINE_CONSTANT(target, GL_LOAD);
#endif

    #ifdef GL_MULT
NODE_DEFINE_CONSTANT(target, GL_MULT);
#endif

    #ifdef GL_RETURN
NODE_DEFINE_CONSTANT(target, GL_RETURN);
#endif

    #ifdef GL_ALPHA_TEST
NODE_DEFINE_CONSTANT(target, GL_ALPHA_TEST);
#endif

    #ifdef GL_ALPHA_TEST_REF
NODE_DEFINE_CONSTANT(target, GL_ALPHA_TEST_REF);
#endif

    #ifdef GL_ALPHA_TEST_FUNC
NODE_DEFINE_CONSTANT(target, GL_ALPHA_TEST_FUNC);
#endif

    #ifdef GL_BLEND
NODE_DEFINE_CONSTANT(target, GL_BLEND);
#endif

    #ifdef GL_BLEND_SRC
NODE_DEFINE_CONSTANT(target, GL_BLEND_SRC);
#endif

    #ifdef GL_BLEND_DST
NODE_DEFINE_CONSTANT(target, GL_BLEND_DST);
#endif

    #ifdef GL_ZERO
NODE_DEFINE_CONSTANT(target, GL_ZERO);
#endif

    #ifdef GL_ONE
NODE_DEFINE_CONSTANT(target, GL_ONE);
#endif

    #ifdef GL_SRC_COLOR
NODE_DEFINE_CONSTANT(target, GL_SRC_COLOR);
#endif

    #ifdef GL_ONE_MINUS_SRC_COLOR
NODE_DEFINE_CONSTANT(target, GL_ONE_MINUS_SRC_COLOR);
#endif

    #ifdef GL_SRC_ALPHA
NODE_DEFINE_CONSTANT(target, GL_SRC_ALPHA);
#endif

    #ifdef GL_ONE_MINUS_SRC_ALPHA
NODE_DEFINE_CONSTANT(target, GL_ONE_MINUS_SRC_ALPHA);
#endif

    #ifdef GL_DST_ALPHA
NODE_DEFINE_CONSTANT(target, GL_DST_ALPHA);
#endif

    #ifdef GL_ONE_MINUS_DST_ALPHA
NODE_DEFINE_CONSTANT(target, GL_ONE_MINUS_DST_ALPHA);
#endif

    #ifdef GL_DST_COLOR
NODE_DEFINE_CONSTANT(target, GL_DST_COLOR);
#endif

    #ifdef GL_ONE_MINUS_DST_COLOR
NODE_DEFINE_CONSTANT(target, GL_ONE_MINUS_DST_COLOR);
#endif

    #ifdef GL_SRC_ALPHA_SATURATE
NODE_DEFINE_CONSTANT(target, GL_SRC_ALPHA_SATURATE);
#endif

    #ifdef GL_FEEDBACK
NODE_DEFINE_CONSTANT(target, GL_FEEDBACK);
#endif

    #ifdef GL_RENDER
NODE_DEFINE_CONSTANT(target, GL_RENDER);
#endif

    #ifdef GL_SELECT
NODE_DEFINE_CONSTANT(target, GL_SELECT);
#endif

    #ifdef GL_2D
NODE_DEFINE_CONSTANT(target, GL_2D);
#endif

    #ifdef GL_3D
NODE_DEFINE_CONSTANT(target, GL_3D);
#endif

    #ifdef GL_3D_COLOR
NODE_DEFINE_CONSTANT(target, GL_3D_COLOR);
#endif

    #ifdef GL_3D_COLOR_TEXTURE
NODE_DEFINE_CONSTANT(target, GL_3D_COLOR_TEXTURE);
#endif

    #ifdef GL_4D_COLOR_TEXTURE
NODE_DEFINE_CONSTANT(target, GL_4D_COLOR_TEXTURE);
#endif

    #ifdef GL_POINT_TOKEN
NODE_DEFINE_CONSTANT(target, GL_POINT_TOKEN);
#endif

    #ifdef GL_LINE_TOKEN
NODE_DEFINE_CONSTANT(target, GL_LINE_TOKEN);
#endif

    #ifdef GL_LINE_RESET_TOKEN
NODE_DEFINE_CONSTANT(target, GL_LINE_RESET_TOKEN);
#endif

    #ifdef GL_POLYGON_TOKEN
NODE_DEFINE_CONSTANT(target, GL_POLYGON_TOKEN);
#endif

    #ifdef GL_BITMAP_TOKEN
NODE_DEFINE_CONSTANT(target, GL_BITMAP_TOKEN);
#endif

    #ifdef GL_DRAW_PIXEL_TOKEN
NODE_DEFINE_CONSTANT(target, GL_DRAW_PIXEL_TOKEN);
#endif

    #ifdef GL_COPY_PIXEL_TOKEN
NODE_DEFINE_CONSTANT(target, GL_COPY_PIXEL_TOKEN);
#endif

    #ifdef GL_PASS_THROUGH_TOKEN
NODE_DEFINE_CONSTANT(target, GL_PASS_THROUGH_TOKEN);
#endif

    #ifdef GL_FEEDBACK_BUFFER_POINTER
NODE_DEFINE_CONSTANT(target, GL_FEEDBACK_BUFFER_POINTER);
#endif

    #ifdef GL_FEEDBACK_BUFFER_SIZE
NODE_DEFINE_CONSTANT(target, GL_FEEDBACK_BUFFER_SIZE);
#endif

    #ifdef GL_FEEDBACK_BUFFER_TYPE
NODE_DEFINE_CONSTANT(target, GL_FEEDBACK_BUFFER_TYPE);
#endif

    #ifdef GL_SELECTION_BUFFER_POINTER
NODE_DEFINE_CONSTANT(target, GL_SELECTION_BUFFER_POINTER);
#endif

    #ifdef GL_SELECTION_BUFFER_SIZE
NODE_DEFINE_CONSTANT(target, GL_SELECTION_BUFFER_SIZE);
#endif

    #ifdef GL_FOG
NODE_DEFINE_CONSTANT(target, GL_FOG);
#endif

    #ifdef GL_FOG_MODE
NODE_DEFINE_CONSTANT(target, GL_FOG_MODE);
#endif

    #ifdef GL_FOG_DENSITY
NODE_DEFINE_CONSTANT(target, GL_FOG_DENSITY);
#endif

    #ifdef GL_FOG_COLOR
NODE_DEFINE_CONSTANT(target, GL_FOG_COLOR);
#endif

    #ifdef GL_FOG_INDEX
NODE_DEFINE_CONSTANT(target, GL_FOG_INDEX);
#endif

    #ifdef GL_FOG_START
NODE_DEFINE_CONSTANT(target, GL_FOG_START);
#endif

    #ifdef GL_FOG_END
NODE_DEFINE_CONSTANT(target, GL_FOG_END);
#endif

    #ifdef GL_LINEAR
NODE_DEFINE_CONSTANT(target, GL_LINEAR);
#endif

    #ifdef GL_EXP
NODE_DEFINE_CONSTANT(target, GL_EXP);
#endif

    #ifdef GL_EXP2
NODE_DEFINE_CONSTANT(target, GL_EXP2);
#endif

    #ifdef GL_LOGIC_OP
NODE_DEFINE_CONSTANT(target, GL_LOGIC_OP);
#endif

    #ifdef GL_INDEX_LOGIC_OP
NODE_DEFINE_CONSTANT(target, GL_INDEX_LOGIC_OP);
#endif

    #ifdef GL_COLOR_LOGIC_OP
NODE_DEFINE_CONSTANT(target, GL_COLOR_LOGIC_OP);
#endif

    #ifdef GL_LOGIC_OP_MODE
NODE_DEFINE_CONSTANT(target, GL_LOGIC_OP_MODE);
#endif

    #ifdef GL_CLEAR
NODE_DEFINE_CONSTANT(target, GL_CLEAR);
#endif

    #ifdef GL_SET
NODE_DEFINE_CONSTANT(target, GL_SET);
#endif

    #ifdef GL_COPY
NODE_DEFINE_CONSTANT(target, GL_COPY);
#endif

    #ifdef GL_COPY_INVERTED
NODE_DEFINE_CONSTANT(target, GL_COPY_INVERTED);
#endif

    #ifdef GL_NOOP
NODE_DEFINE_CONSTANT(target, GL_NOOP);
#endif

    #ifdef GL_INVERT
NODE_DEFINE_CONSTANT(target, GL_INVERT);
#endif

    #ifdef GL_AND
NODE_DEFINE_CONSTANT(target, GL_AND);
#endif

    #ifdef GL_NAND
NODE_DEFINE_CONSTANT(target, GL_NAND);
#endif

    #ifdef GL_OR
NODE_DEFINE_CONSTANT(target, GL_OR);
#endif

    #ifdef GL_NOR
NODE_DEFINE_CONSTANT(target, GL_NOR);
#endif

    #ifdef GL_XOR
NODE_DEFINE_CONSTANT(target, GL_XOR);
#endif

    #ifdef GL_EQUIV
NODE_DEFINE_CONSTANT(target, GL_EQUIV);
#endif

    #ifdef GL_AND_REVERSE
NODE_DEFINE_CONSTANT(target, GL_AND_REVERSE);
#endif

    #ifdef GL_AND_INVERTED
NODE_DEFINE_CONSTANT(target, GL_AND_INVERTED);
#endif

    #ifdef GL_OR_REVERSE
NODE_DEFINE_CONSTANT(target, GL_OR_REVERSE);
#endif

    #ifdef GL_OR_INVERTED
NODE_DEFINE_CONSTANT(target, GL_OR_INVERTED);
#endif

    #ifdef GL_STENCIL_BITS
NODE_DEFINE_CONSTANT(target, GL_STENCIL_BITS);
#endif

    #ifdef GL_STENCIL_TEST
NODE_DEFINE_CONSTANT(target, GL_STENCIL_TEST);
#endif

    #ifdef GL_STENCIL_CLEAR_VALUE
NODE_DEFINE_CONSTANT(target, GL_STENCIL_CLEAR_VALUE);
#endif

    #ifdef GL_STENCIL_FUNC
NODE_DEFINE_CONSTANT(target, GL_STENCIL_FUNC);
#endif

    #ifdef GL_STENCIL_VALUE_MASK
NODE_DEFINE_CONSTANT(target, GL_STENCIL_VALUE_MASK);
#endif

    #ifdef GL_STENCIL_FAIL
NODE_DEFINE_CONSTANT(target, GL_STENCIL_FAIL);
#endif

    #ifdef GL_STENCIL_PASS_DEPTH_FAIL
NODE_DEFINE_CONSTANT(target, GL_STENCIL_PASS_DEPTH_FAIL);
#endif

    #ifdef GL_STENCIL_PASS_DEPTH_PASS
NODE_DEFINE_CONSTANT(target, GL_STENCIL_PASS_DEPTH_PASS);
#endif

    #ifdef GL_STENCIL_REF
NODE_DEFINE_CONSTANT(target, GL_STENCIL_REF);
#endif

    #ifdef GL_STENCIL_WRITEMASK
NODE_DEFINE_CONSTANT(target, GL_STENCIL_WRITEMASK);
#endif

    #ifdef GL_STENCIL_INDEX
NODE_DEFINE_CONSTANT(target, GL_STENCIL_INDEX);
#endif

    #ifdef GL_KEEP
NODE_DEFINE_CONSTANT(target, GL_KEEP);
#endif

    #ifdef GL_REPLACE
NODE_DEFINE_CONSTANT(target, GL_REPLACE);
#endif

    #ifdef GL_INCR
NODE_DEFINE_CONSTANT(target, GL_INCR);
#endif

    #ifdef GL_DECR
NODE_DEFINE_CONSTANT(target, GL_DECR);
#endif

    #ifdef GL_NONE
NODE_DEFINE_CONSTANT(target, GL_NONE);
#endif

    #ifdef GL_LEFT
NODE_DEFINE_CONSTANT(target, GL_LEFT);
#endif

    #ifdef GL_RIGHT
NODE_DEFINE_CONSTANT(target, GL_RIGHT);
#endif

    #ifdef GL_FRONT_LEFT
NODE_DEFINE_CONSTANT(target, GL_FRONT_LEFT);
#endif

    #ifdef GL_FRONT_RIGHT
NODE_DEFINE_CONSTANT(target, GL_FRONT_RIGHT);
#endif

    #ifdef GL_BACK_LEFT
NODE_DEFINE_CONSTANT(target, GL_BACK_LEFT);
#endif

    #ifdef GL_BACK_RIGHT
NODE_DEFINE_CONSTANT(target, GL_BACK_RIGHT);
#endif

    #ifdef GL_AUX0
NODE_DEFINE_CONSTANT(target, GL_AUX0);
#endif

    #ifdef GL_AUX1
NODE_DEFINE_CONSTANT(target, GL_AUX1);
#endif

    #ifdef GL_AUX2
NODE_DEFINE_CONSTANT(target, GL_AUX2);
#endif

    #ifdef GL_AUX3
NODE_DEFINE_CONSTANT(target, GL_AUX3);
#endif

    #ifdef GL_COLOR_INDEX
NODE_DEFINE_CONSTANT(target, GL_COLOR_INDEX);
#endif

    #ifdef GL_RED
NODE_DEFINE_CONSTANT(target, GL_RED);
#endif

    #ifdef GL_GREEN
NODE_DEFINE_CONSTANT(target, GL_GREEN);
#endif

    #ifdef GL_BLUE
NODE_DEFINE_CONSTANT(target, GL_BLUE);
#endif

    #ifdef GL_ALPHA
NODE_DEFINE_CONSTANT(target, GL_ALPHA);
#endif

    #ifdef GL_LUMINANCE
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE);
#endif

    #ifdef GL_LUMINANCE_ALPHA
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE_ALPHA);
#endif

    #ifdef GL_ALPHA_BITS
NODE_DEFINE_CONSTANT(target, GL_ALPHA_BITS);
#endif

    #ifdef GL_RED_BITS
NODE_DEFINE_CONSTANT(target, GL_RED_BITS);
#endif

    #ifdef GL_GREEN_BITS
NODE_DEFINE_CONSTANT(target, GL_GREEN_BITS);
#endif

    #ifdef GL_BLUE_BITS
NODE_DEFINE_CONSTANT(target, GL_BLUE_BITS);
#endif

    #ifdef GL_INDEX_BITS
NODE_DEFINE_CONSTANT(target, GL_INDEX_BITS);
#endif

    #ifdef GL_SUBPIXEL_BITS
NODE_DEFINE_CONSTANT(target, GL_SUBPIXEL_BITS);
#endif

    #ifdef GL_AUX_BUFFERS
NODE_DEFINE_CONSTANT(target, GL_AUX_BUFFERS);
#endif

    #ifdef GL_READ_BUFFER
NODE_DEFINE_CONSTANT(target, GL_READ_BUFFER);
#endif

    #ifdef GL_DRAW_BUFFER
NODE_DEFINE_CONSTANT(target, GL_DRAW_BUFFER);
#endif

    #ifdef GL_DOUBLEBUFFER
NODE_DEFINE_CONSTANT(target, GL_DOUBLEBUFFER);
#endif

    #ifdef GL_STEREO
NODE_DEFINE_CONSTANT(target, GL_STEREO);
#endif

    #ifdef GL_BITMAP
NODE_DEFINE_CONSTANT(target, GL_BITMAP);
#endif

    #ifdef GL_COLOR
NODE_DEFINE_CONSTANT(target, GL_COLOR);
#endif

    #ifdef GL_DEPTH
NODE_DEFINE_CONSTANT(target, GL_DEPTH);
#endif

    #ifdef GL_STENCIL
NODE_DEFINE_CONSTANT(target, GL_STENCIL);
#endif

    #ifdef GL_DITHER
NODE_DEFINE_CONSTANT(target, GL_DITHER);
#endif

    #ifdef GL_RGB
NODE_DEFINE_CONSTANT(target, GL_RGB);
#endif

    #ifdef GL_RGBA
NODE_DEFINE_CONSTANT(target, GL_RGBA);
#endif

    #ifdef GL_MAX_LIST_NESTING
NODE_DEFINE_CONSTANT(target, GL_MAX_LIST_NESTING);
#endif

    #ifdef GL_MAX_EVAL_ORDER
NODE_DEFINE_CONSTANT(target, GL_MAX_EVAL_ORDER);
#endif

    #ifdef GL_MAX_LIGHTS
NODE_DEFINE_CONSTANT(target, GL_MAX_LIGHTS);
#endif

    #ifdef GL_MAX_CLIP_PLANES
NODE_DEFINE_CONSTANT(target, GL_MAX_CLIP_PLANES);
#endif

    #ifdef GL_MAX_TEXTURE_SIZE
NODE_DEFINE_CONSTANT(target, GL_MAX_TEXTURE_SIZE);
#endif

    #ifdef GL_MAX_PIXEL_MAP_TABLE
NODE_DEFINE_CONSTANT(target, GL_MAX_PIXEL_MAP_TABLE);
#endif

    #ifdef GL_MAX_ATTRIB_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_MAX_ATTRIB_STACK_DEPTH);
#endif

    #ifdef GL_MAX_MODELVIEW_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_MAX_MODELVIEW_STACK_DEPTH);
#endif

    #ifdef GL_MAX_NAME_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_MAX_NAME_STACK_DEPTH);
#endif

    #ifdef GL_MAX_PROJECTION_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_MAX_PROJECTION_STACK_DEPTH);
#endif

    #ifdef GL_MAX_TEXTURE_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_MAX_TEXTURE_STACK_DEPTH);
#endif

    #ifdef GL_MAX_VIEWPORT_DIMS
NODE_DEFINE_CONSTANT(target, GL_MAX_VIEWPORT_DIMS);
#endif

    #ifdef GL_MAX_CLIENT_ATTRIB_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_MAX_CLIENT_ATTRIB_STACK_DEPTH);
#endif

    #ifdef GL_ATTRIB_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_ATTRIB_STACK_DEPTH);
#endif

    #ifdef GL_CLIENT_ATTRIB_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_CLIENT_ATTRIB_STACK_DEPTH);
#endif

    #ifdef GL_COLOR_CLEAR_VALUE
NODE_DEFINE_CONSTANT(target, GL_COLOR_CLEAR_VALUE);
#endif

    #ifdef GL_COLOR_WRITEMASK
NODE_DEFINE_CONSTANT(target, GL_COLOR_WRITEMASK);
#endif

    #ifdef GL_CURRENT_INDEX
NODE_DEFINE_CONSTANT(target, GL_CURRENT_INDEX);
#endif

    #ifdef GL_CURRENT_COLOR
NODE_DEFINE_CONSTANT(target, GL_CURRENT_COLOR);
#endif

    #ifdef GL_CURRENT_NORMAL
NODE_DEFINE_CONSTANT(target, GL_CURRENT_NORMAL);
#endif

    #ifdef GL_CURRENT_RASTER_COLOR
NODE_DEFINE_CONSTANT(target, GL_CURRENT_RASTER_COLOR);
#endif

    #ifdef GL_CURRENT_RASTER_DISTANCE
NODE_DEFINE_CONSTANT(target, GL_CURRENT_RASTER_DISTANCE);
#endif

    #ifdef GL_CURRENT_RASTER_INDEX
NODE_DEFINE_CONSTANT(target, GL_CURRENT_RASTER_INDEX);
#endif

    #ifdef GL_CURRENT_RASTER_POSITION
NODE_DEFINE_CONSTANT(target, GL_CURRENT_RASTER_POSITION);
#endif

    #ifdef GL_CURRENT_RASTER_TEXTURE_COORDS
NODE_DEFINE_CONSTANT(target, GL_CURRENT_RASTER_TEXTURE_COORDS);
#endif

    #ifdef GL_CURRENT_RASTER_POSITION_VALID
NODE_DEFINE_CONSTANT(target, GL_CURRENT_RASTER_POSITION_VALID);
#endif

    #ifdef GL_CURRENT_TEXTURE_COORDS
NODE_DEFINE_CONSTANT(target, GL_CURRENT_TEXTURE_COORDS);
#endif

    #ifdef GL_INDEX_CLEAR_VALUE
NODE_DEFINE_CONSTANT(target, GL_INDEX_CLEAR_VALUE);
#endif

    #ifdef GL_INDEX_MODE
NODE_DEFINE_CONSTANT(target, GL_INDEX_MODE);
#endif

    #ifdef GL_INDEX_WRITEMASK
NODE_DEFINE_CONSTANT(target, GL_INDEX_WRITEMASK);
#endif

    #ifdef GL_MODELVIEW_MATRIX
NODE_DEFINE_CONSTANT(target, GL_MODELVIEW_MATRIX);
#endif

    #ifdef GL_MODELVIEW_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_MODELVIEW_STACK_DEPTH);
#endif

    #ifdef GL_NAME_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_NAME_STACK_DEPTH);
#endif

    #ifdef GL_PROJECTION_MATRIX
NODE_DEFINE_CONSTANT(target, GL_PROJECTION_MATRIX);
#endif

    #ifdef GL_PROJECTION_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_PROJECTION_STACK_DEPTH);
#endif

    #ifdef GL_RENDER_MODE
NODE_DEFINE_CONSTANT(target, GL_RENDER_MODE);
#endif

    #ifdef GL_RGBA_MODE
NODE_DEFINE_CONSTANT(target, GL_RGBA_MODE);
#endif

    #ifdef GL_TEXTURE_MATRIX
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_MATRIX);
#endif

    #ifdef GL_TEXTURE_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_STACK_DEPTH);
#endif

    #ifdef GL_VIEWPORT
NODE_DEFINE_CONSTANT(target, GL_VIEWPORT);
#endif

    #ifdef GL_AUTO_NORMAL
NODE_DEFINE_CONSTANT(target, GL_AUTO_NORMAL);
#endif

    #ifdef GL_MAP1_COLOR_4
NODE_DEFINE_CONSTANT(target, GL_MAP1_COLOR_4);
#endif

    #ifdef GL_MAP1_INDEX
NODE_DEFINE_CONSTANT(target, GL_MAP1_INDEX);
#endif

    #ifdef GL_MAP1_NORMAL
NODE_DEFINE_CONSTANT(target, GL_MAP1_NORMAL);
#endif

    #ifdef GL_MAP1_TEXTURE_COORD_1
NODE_DEFINE_CONSTANT(target, GL_MAP1_TEXTURE_COORD_1);
#endif

    #ifdef GL_MAP1_TEXTURE_COORD_2
NODE_DEFINE_CONSTANT(target, GL_MAP1_TEXTURE_COORD_2);
#endif

    #ifdef GL_MAP1_TEXTURE_COORD_3
NODE_DEFINE_CONSTANT(target, GL_MAP1_TEXTURE_COORD_3);
#endif

    #ifdef GL_MAP1_TEXTURE_COORD_4
NODE_DEFINE_CONSTANT(target, GL_MAP1_TEXTURE_COORD_4);
#endif

    #ifdef GL_MAP1_VERTEX_3
NODE_DEFINE_CONSTANT(target, GL_MAP1_VERTEX_3);
#endif

    #ifdef GL_MAP1_VERTEX_4
NODE_DEFINE_CONSTANT(target, GL_MAP1_VERTEX_4);
#endif

    #ifdef GL_MAP2_COLOR_4
NODE_DEFINE_CONSTANT(target, GL_MAP2_COLOR_4);
#endif

    #ifdef GL_MAP2_INDEX
NODE_DEFINE_CONSTANT(target, GL_MAP2_INDEX);
#endif

    #ifdef GL_MAP2_NORMAL
NODE_DEFINE_CONSTANT(target, GL_MAP2_NORMAL);
#endif

    #ifdef GL_MAP2_TEXTURE_COORD_1
NODE_DEFINE_CONSTANT(target, GL_MAP2_TEXTURE_COORD_1);
#endif

    #ifdef GL_MAP2_TEXTURE_COORD_2
NODE_DEFINE_CONSTANT(target, GL_MAP2_TEXTURE_COORD_2);
#endif

    #ifdef GL_MAP2_TEXTURE_COORD_3
NODE_DEFINE_CONSTANT(target, GL_MAP2_TEXTURE_COORD_3);
#endif

    #ifdef GL_MAP2_TEXTURE_COORD_4
NODE_DEFINE_CONSTANT(target, GL_MAP2_TEXTURE_COORD_4);
#endif

    #ifdef GL_MAP2_VERTEX_3
NODE_DEFINE_CONSTANT(target, GL_MAP2_VERTEX_3);
#endif

    #ifdef GL_MAP2_VERTEX_4
NODE_DEFINE_CONSTANT(target, GL_MAP2_VERTEX_4);
#endif

    #ifdef GL_MAP1_GRID_DOMAIN
NODE_DEFINE_CONSTANT(target, GL_MAP1_GRID_DOMAIN);
#endif

    #ifdef GL_MAP1_GRID_SEGMENTS
NODE_DEFINE_CONSTANT(target, GL_MAP1_GRID_SEGMENTS);
#endif

    #ifdef GL_MAP2_GRID_DOMAIN
NODE_DEFINE_CONSTANT(target, GL_MAP2_GRID_DOMAIN);
#endif

    #ifdef GL_MAP2_GRID_SEGMENTS
NODE_DEFINE_CONSTANT(target, GL_MAP2_GRID_SEGMENTS);
#endif

    #ifdef GL_COEFF
NODE_DEFINE_CONSTANT(target, GL_COEFF);
#endif

    #ifdef GL_ORDER
NODE_DEFINE_CONSTANT(target, GL_ORDER);
#endif

    #ifdef GL_DOMAIN
NODE_DEFINE_CONSTANT(target, GL_DOMAIN);
#endif

    #ifdef GL_PERSPECTIVE_CORRECTION_HINT
NODE_DEFINE_CONSTANT(target, GL_PERSPECTIVE_CORRECTION_HINT);
#endif

    #ifdef GL_POINT_SMOOTH_HINT
NODE_DEFINE_CONSTANT(target, GL_POINT_SMOOTH_HINT);
#endif

    #ifdef GL_LINE_SMOOTH_HINT
NODE_DEFINE_CONSTANT(target, GL_LINE_SMOOTH_HINT);
#endif

    #ifdef GL_POLYGON_SMOOTH_HINT
NODE_DEFINE_CONSTANT(target, GL_POLYGON_SMOOTH_HINT);
#endif

    #ifdef GL_FOG_HINT
NODE_DEFINE_CONSTANT(target, GL_FOG_HINT);
#endif

    #ifdef GL_DONT_CARE
NODE_DEFINE_CONSTANT(target, GL_DONT_CARE);
#endif

    #ifdef GL_FASTEST
NODE_DEFINE_CONSTANT(target, GL_FASTEST);
#endif

    #ifdef GL_NICEST
NODE_DEFINE_CONSTANT(target, GL_NICEST);
#endif

    #ifdef GL_SCISSOR_BOX
NODE_DEFINE_CONSTANT(target, GL_SCISSOR_BOX);
#endif

    #ifdef GL_SCISSOR_TEST
NODE_DEFINE_CONSTANT(target, GL_SCISSOR_TEST);
#endif

    #ifdef GL_MAP_COLOR
NODE_DEFINE_CONSTANT(target, GL_MAP_COLOR);
#endif

    #ifdef GL_MAP_STENCIL
NODE_DEFINE_CONSTANT(target, GL_MAP_STENCIL);
#endif

    #ifdef GL_INDEX_SHIFT
NODE_DEFINE_CONSTANT(target, GL_INDEX_SHIFT);
#endif

    #ifdef GL_INDEX_OFFSET
NODE_DEFINE_CONSTANT(target, GL_INDEX_OFFSET);
#endif

    #ifdef GL_RED_SCALE
NODE_DEFINE_CONSTANT(target, GL_RED_SCALE);
#endif

    #ifdef GL_RED_BIAS
NODE_DEFINE_CONSTANT(target, GL_RED_BIAS);
#endif

    #ifdef GL_GREEN_SCALE
NODE_DEFINE_CONSTANT(target, GL_GREEN_SCALE);
#endif

    #ifdef GL_GREEN_BIAS
NODE_DEFINE_CONSTANT(target, GL_GREEN_BIAS);
#endif

    #ifdef GL_BLUE_SCALE
NODE_DEFINE_CONSTANT(target, GL_BLUE_SCALE);
#endif

    #ifdef GL_BLUE_BIAS
NODE_DEFINE_CONSTANT(target, GL_BLUE_BIAS);
#endif

    #ifdef GL_ALPHA_SCALE
NODE_DEFINE_CONSTANT(target, GL_ALPHA_SCALE);
#endif

    #ifdef GL_ALPHA_BIAS
NODE_DEFINE_CONSTANT(target, GL_ALPHA_BIAS);
#endif

    #ifdef GL_DEPTH_SCALE
NODE_DEFINE_CONSTANT(target, GL_DEPTH_SCALE);
#endif

    #ifdef GL_DEPTH_BIAS
NODE_DEFINE_CONSTANT(target, GL_DEPTH_BIAS);
#endif

    #ifdef GL_PIXEL_MAP_S_TO_S_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_S_TO_S_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_I_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_I_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_R_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_R_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_G_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_G_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_B_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_B_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_A_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_A_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_R_TO_R_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_R_TO_R_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_G_TO_G_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_G_TO_G_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_B_TO_B_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_B_TO_B_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_A_TO_A_SIZE
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_A_TO_A_SIZE);
#endif

    #ifdef GL_PIXEL_MAP_S_TO_S
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_S_TO_S);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_I
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_I);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_R
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_R);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_G
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_G);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_B
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_B);
#endif

    #ifdef GL_PIXEL_MAP_I_TO_A
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_I_TO_A);
#endif

    #ifdef GL_PIXEL_MAP_R_TO_R
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_R_TO_R);
#endif

    #ifdef GL_PIXEL_MAP_G_TO_G
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_G_TO_G);
#endif

    #ifdef GL_PIXEL_MAP_B_TO_B
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_B_TO_B);
#endif

    #ifdef GL_PIXEL_MAP_A_TO_A
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MAP_A_TO_A);
#endif

    #ifdef GL_PACK_ALIGNMENT
NODE_DEFINE_CONSTANT(target, GL_PACK_ALIGNMENT);
#endif

    #ifdef GL_PACK_LSB_FIRST
NODE_DEFINE_CONSTANT(target, GL_PACK_LSB_FIRST);
#endif

    #ifdef GL_PACK_ROW_LENGTH
NODE_DEFINE_CONSTANT(target, GL_PACK_ROW_LENGTH);
#endif

    #ifdef GL_PACK_SKIP_PIXELS
NODE_DEFINE_CONSTANT(target, GL_PACK_SKIP_PIXELS);
#endif

    #ifdef GL_PACK_SKIP_ROWS
NODE_DEFINE_CONSTANT(target, GL_PACK_SKIP_ROWS);
#endif

    #ifdef GL_PACK_SWAP_BYTES
NODE_DEFINE_CONSTANT(target, GL_PACK_SWAP_BYTES);
#endif

    #ifdef GL_UNPACK_ALIGNMENT
NODE_DEFINE_CONSTANT(target, GL_UNPACK_ALIGNMENT);
#endif

    #ifdef GL_UNPACK_LSB_FIRST
NODE_DEFINE_CONSTANT(target, GL_UNPACK_LSB_FIRST);
#endif

    #ifdef GL_UNPACK_ROW_LENGTH
NODE_DEFINE_CONSTANT(target, GL_UNPACK_ROW_LENGTH);
#endif

    #ifdef GL_UNPACK_SKIP_PIXELS
NODE_DEFINE_CONSTANT(target, GL_UNPACK_SKIP_PIXELS);
#endif

    #ifdef GL_UNPACK_SKIP_ROWS
NODE_DEFINE_CONSTANT(target, GL_UNPACK_SKIP_ROWS);
#endif

    #ifdef GL_UNPACK_SWAP_BYTES
NODE_DEFINE_CONSTANT(target, GL_UNPACK_SWAP_BYTES);
#endif

    #ifdef GL_ZOOM_X
NODE_DEFINE_CONSTANT(target, GL_ZOOM_X);
#endif

    #ifdef GL_ZOOM_Y
NODE_DEFINE_CONSTANT(target, GL_ZOOM_Y);
#endif

    #ifdef GL_TEXTURE_ENV
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_ENV);
#endif

    #ifdef GL_TEXTURE_ENV_MODE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_ENV_MODE);
#endif

    #ifdef GL_TEXTURE_1D
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_1D);
#endif

    #ifdef GL_TEXTURE_2D
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_2D);
#endif

    #ifdef GL_TEXTURE_WRAP_S
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_WRAP_S);
#endif

    #ifdef GL_TEXTURE_WRAP_T
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_WRAP_T);
#endif

    #ifdef GL_TEXTURE_MAG_FILTER
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_MAG_FILTER);
#endif

    #ifdef GL_TEXTURE_MIN_FILTER
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_MIN_FILTER);
#endif

    #ifdef GL_TEXTURE_ENV_COLOR
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_ENV_COLOR);
#endif

    #ifdef GL_TEXTURE_GEN_S
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_GEN_S);
#endif

    #ifdef GL_TEXTURE_GEN_T
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_GEN_T);
#endif

    #ifdef GL_TEXTURE_GEN_MODE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_GEN_MODE);
#endif

    #ifdef GL_TEXTURE_BORDER_COLOR
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BORDER_COLOR);
#endif

    #ifdef GL_TEXTURE_WIDTH
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_WIDTH);
#endif

    #ifdef GL_TEXTURE_HEIGHT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_HEIGHT);
#endif

    #ifdef GL_TEXTURE_BORDER
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BORDER);
#endif

    #ifdef GL_TEXTURE_COMPONENTS
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COMPONENTS);
#endif

    #ifdef GL_TEXTURE_RED_SIZE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_RED_SIZE);
#endif

    #ifdef GL_TEXTURE_GREEN_SIZE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_GREEN_SIZE);
#endif

    #ifdef GL_TEXTURE_BLUE_SIZE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BLUE_SIZE);
#endif

    #ifdef GL_TEXTURE_ALPHA_SIZE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_ALPHA_SIZE);
#endif

    #ifdef GL_TEXTURE_LUMINANCE_SIZE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_LUMINANCE_SIZE);
#endif

    #ifdef GL_TEXTURE_INTENSITY_SIZE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_INTENSITY_SIZE);
#endif

    #ifdef GL_NEAREST_MIPMAP_NEAREST
NODE_DEFINE_CONSTANT(target, GL_NEAREST_MIPMAP_NEAREST);
#endif

    #ifdef GL_NEAREST_MIPMAP_LINEAR
NODE_DEFINE_CONSTANT(target, GL_NEAREST_MIPMAP_LINEAR);
#endif

    #ifdef GL_LINEAR_MIPMAP_NEAREST
NODE_DEFINE_CONSTANT(target, GL_LINEAR_MIPMAP_NEAREST);
#endif

    #ifdef GL_LINEAR_MIPMAP_LINEAR
NODE_DEFINE_CONSTANT(target, GL_LINEAR_MIPMAP_LINEAR);
#endif

    #ifdef GL_OBJECT_LINEAR
NODE_DEFINE_CONSTANT(target, GL_OBJECT_LINEAR);
#endif

    #ifdef GL_OBJECT_PLANE
NODE_DEFINE_CONSTANT(target, GL_OBJECT_PLANE);
#endif

    #ifdef GL_EYE_LINEAR
NODE_DEFINE_CONSTANT(target, GL_EYE_LINEAR);
#endif

    #ifdef GL_EYE_PLANE
NODE_DEFINE_CONSTANT(target, GL_EYE_PLANE);
#endif

    #ifdef GL_SPHERE_MAP
NODE_DEFINE_CONSTANT(target, GL_SPHERE_MAP);
#endif

    #ifdef GL_DECAL
NODE_DEFINE_CONSTANT(target, GL_DECAL);
#endif

    #ifdef GL_MODULATE
NODE_DEFINE_CONSTANT(target, GL_MODULATE);
#endif

    #ifdef GL_NEAREST
NODE_DEFINE_CONSTANT(target, GL_NEAREST);
#endif

    #ifdef GL_REPEAT
NODE_DEFINE_CONSTANT(target, GL_REPEAT);
#endif

    #ifdef GL_CLAMP
NODE_DEFINE_CONSTANT(target, GL_CLAMP);
#endif

    #ifdef GL_S
NODE_DEFINE_CONSTANT(target, GL_S);
#endif

    #ifdef GL_T
NODE_DEFINE_CONSTANT(target, GL_T);
#endif

    #ifdef GL_R
NODE_DEFINE_CONSTANT(target, GL_R);
#endif

    #ifdef GL_Q
NODE_DEFINE_CONSTANT(target, GL_Q);
#endif

    #ifdef GL_TEXTURE_GEN_R
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_GEN_R);
#endif

    #ifdef GL_TEXTURE_GEN_Q
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_GEN_Q);
#endif

    #ifdef GL_VENDOR
NODE_DEFINE_CONSTANT(target, GL_VENDOR);
#endif

    #ifdef GL_RENDERER
NODE_DEFINE_CONSTANT(target, GL_RENDERER);
#endif

    #ifdef GL_VERSION
NODE_DEFINE_CONSTANT(target, GL_VERSION);
#endif

    #ifdef GL_EXTENSIONS
NODE_DEFINE_CONSTANT(target, GL_EXTENSIONS);
#endif

    #ifdef GL_NO_ERROR
NODE_DEFINE_CONSTANT(target, GL_NO_ERROR);
#endif

    #ifdef GL_INVALID_ENUM
NODE_DEFINE_CONSTANT(target, GL_INVALID_ENUM);
#endif

    #ifdef GL_INVALID_VALUE
NODE_DEFINE_CONSTANT(target, GL_INVALID_VALUE);
#endif

    #ifdef GL_INVALID_OPERATION
NODE_DEFINE_CONSTANT(target, GL_INVALID_OPERATION);
#endif

    #ifdef GL_STACK_OVERFLOW
NODE_DEFINE_CONSTANT(target, GL_STACK_OVERFLOW);
#endif

    #ifdef GL_STACK_UNDERFLOW
NODE_DEFINE_CONSTANT(target, GL_STACK_UNDERFLOW);
#endif

    #ifdef GL_OUT_OF_MEMORY
NODE_DEFINE_CONSTANT(target, GL_OUT_OF_MEMORY);
#endif

    #ifdef GL_CURRENT_BIT
NODE_DEFINE_CONSTANT(target, GL_CURRENT_BIT);
#endif

    #ifdef GL_POINT_BIT
NODE_DEFINE_CONSTANT(target, GL_POINT_BIT);
#endif

    #ifdef GL_LINE_BIT
NODE_DEFINE_CONSTANT(target, GL_LINE_BIT);
#endif

    #ifdef GL_POLYGON_BIT
NODE_DEFINE_CONSTANT(target, GL_POLYGON_BIT);
#endif

    #ifdef GL_POLYGON_STIPPLE_BIT
NODE_DEFINE_CONSTANT(target, GL_POLYGON_STIPPLE_BIT);
#endif

    #ifdef GL_PIXEL_MODE_BIT
NODE_DEFINE_CONSTANT(target, GL_PIXEL_MODE_BIT);
#endif

    #ifdef GL_LIGHTING_BIT
NODE_DEFINE_CONSTANT(target, GL_LIGHTING_BIT);
#endif

    #ifdef GL_FOG_BIT
NODE_DEFINE_CONSTANT(target, GL_FOG_BIT);
#endif

    #ifdef GL_DEPTH_BUFFER_BIT
NODE_DEFINE_CONSTANT(target, GL_DEPTH_BUFFER_BIT);
#endif

    #ifdef GL_ACCUM_BUFFER_BIT
NODE_DEFINE_CONSTANT(target, GL_ACCUM_BUFFER_BIT);
#endif

    #ifdef GL_STENCIL_BUFFER_BIT
NODE_DEFINE_CONSTANT(target, GL_STENCIL_BUFFER_BIT);
#endif

    #ifdef GL_VIEWPORT_BIT
NODE_DEFINE_CONSTANT(target, GL_VIEWPORT_BIT);
#endif

    #ifdef GL_TRANSFORM_BIT
NODE_DEFINE_CONSTANT(target, GL_TRANSFORM_BIT);
#endif

    #ifdef GL_ENABLE_BIT
NODE_DEFINE_CONSTANT(target, GL_ENABLE_BIT);
#endif

    #ifdef GL_COLOR_BUFFER_BIT
NODE_DEFINE_CONSTANT(target, GL_COLOR_BUFFER_BIT);
#endif

    #ifdef GL_HINT_BIT
NODE_DEFINE_CONSTANT(target, GL_HINT_BIT);
#endif

    #ifdef GL_EVAL_BIT
NODE_DEFINE_CONSTANT(target, GL_EVAL_BIT);
#endif

    #ifdef GL_LIST_BIT
NODE_DEFINE_CONSTANT(target, GL_LIST_BIT);
#endif

    #ifdef GL_TEXTURE_BIT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BIT);
#endif

    #ifdef GL_SCISSOR_BIT
NODE_DEFINE_CONSTANT(target, GL_SCISSOR_BIT);
#endif

    #ifdef GL_ALL_ATTRIB_BITS
NODE_DEFINE_CONSTANT(target, GL_ALL_ATTRIB_BITS);
#endif

    #ifdef GL_PROXY_TEXTURE_1D
NODE_DEFINE_CONSTANT(target, GL_PROXY_TEXTURE_1D);
#endif

    #ifdef GL_PROXY_TEXTURE_2D
NODE_DEFINE_CONSTANT(target, GL_PROXY_TEXTURE_2D);
#endif

    #ifdef GL_TEXTURE_PRIORITY
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_PRIORITY);
#endif

    #ifdef GL_TEXTURE_RESIDENT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_RESIDENT);
#endif

    #ifdef GL_TEXTURE_BINDING_1D
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BINDING_1D);
#endif

    #ifdef GL_TEXTURE_BINDING_2D
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BINDING_2D);
#endif

    #ifdef GL_TEXTURE_INTERNAL_FORMAT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_INTERNAL_FORMAT);
#endif

    #ifdef GL_ALPHA4
NODE_DEFINE_CONSTANT(target, GL_ALPHA4);
#endif

    #ifdef GL_ALPHA8
NODE_DEFINE_CONSTANT(target, GL_ALPHA8);
#endif

    #ifdef GL_ALPHA12
NODE_DEFINE_CONSTANT(target, GL_ALPHA12);
#endif

    #ifdef GL_ALPHA16
NODE_DEFINE_CONSTANT(target, GL_ALPHA16);
#endif

    #ifdef GL_LUMINANCE4
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE4);
#endif

    #ifdef GL_LUMINANCE8
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE8);
#endif

    #ifdef GL_LUMINANCE12
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE12);
#endif

    #ifdef GL_LUMINANCE16
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE16);
#endif

    #ifdef GL_LUMINANCE4_ALPHA4
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE4_ALPHA4);
#endif

    #ifdef GL_LUMINANCE6_ALPHA2
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE6_ALPHA2);
#endif

    #ifdef GL_LUMINANCE8_ALPHA8
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE8_ALPHA8);
#endif

    #ifdef GL_LUMINANCE12_ALPHA4
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE12_ALPHA4);
#endif

    #ifdef GL_LUMINANCE12_ALPHA12
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE12_ALPHA12);
#endif

    #ifdef GL_LUMINANCE16_ALPHA16
NODE_DEFINE_CONSTANT(target, GL_LUMINANCE16_ALPHA16);
#endif

    #ifdef GL_INTENSITY
NODE_DEFINE_CONSTANT(target, GL_INTENSITY);
#endif

    #ifdef GL_INTENSITY4
NODE_DEFINE_CONSTANT(target, GL_INTENSITY4);
#endif

    #ifdef GL_INTENSITY8
NODE_DEFINE_CONSTANT(target, GL_INTENSITY8);
#endif

    #ifdef GL_INTENSITY12
NODE_DEFINE_CONSTANT(target, GL_INTENSITY12);
#endif

    #ifdef GL_INTENSITY16
NODE_DEFINE_CONSTANT(target, GL_INTENSITY16);
#endif

    #ifdef GL_R3_G3_B2
NODE_DEFINE_CONSTANT(target, GL_R3_G3_B2);
#endif

    #ifdef GL_RGB4
NODE_DEFINE_CONSTANT(target, GL_RGB4);
#endif

    #ifdef GL_RGB5
NODE_DEFINE_CONSTANT(target, GL_RGB5);
#endif

    #ifdef GL_RGB8
NODE_DEFINE_CONSTANT(target, GL_RGB8);
#endif

    #ifdef GL_RGB10
NODE_DEFINE_CONSTANT(target, GL_RGB10);
#endif

    #ifdef GL_RGB12
NODE_DEFINE_CONSTANT(target, GL_RGB12);
#endif

    #ifdef GL_RGB16
NODE_DEFINE_CONSTANT(target, GL_RGB16);
#endif

    #ifdef GL_RGBA2
NODE_DEFINE_CONSTANT(target, GL_RGBA2);
#endif

    #ifdef GL_RGBA4
NODE_DEFINE_CONSTANT(target, GL_RGBA4);
#endif

    #ifdef GL_RGB5_A1
NODE_DEFINE_CONSTANT(target, GL_RGB5_A1);
#endif

    #ifdef GL_RGBA8
NODE_DEFINE_CONSTANT(target, GL_RGBA8);
#endif

    #ifdef GL_RGB10_A2
NODE_DEFINE_CONSTANT(target, GL_RGB10_A2);
#endif

    #ifdef GL_RGBA12
NODE_DEFINE_CONSTANT(target, GL_RGBA12);
#endif

    #ifdef GL_RGBA16
NODE_DEFINE_CONSTANT(target, GL_RGBA16);
#endif

    #ifdef GL_CLIENT_PIXEL_STORE_BIT
NODE_DEFINE_CONSTANT(target, GL_CLIENT_PIXEL_STORE_BIT);
#endif

    #ifdef GL_CLIENT_VERTEX_ARRAY_BIT
NODE_DEFINE_CONSTANT(target, GL_CLIENT_VERTEX_ARRAY_BIT);
#endif

    #ifdef GL_ALL_CLIENT_ATTRIB_BITS
NODE_DEFINE_CONSTANT(target, GL_ALL_CLIENT_ATTRIB_BITS);
#endif

    #ifdef GL_CLIENT_ALL_ATTRIB_BITS
NODE_DEFINE_CONSTANT(target, GL_CLIENT_ALL_ATTRIB_BITS);
#endif

    #ifdef GL_RESCALE_NORMAL
NODE_DEFINE_CONSTANT(target, GL_RESCALE_NORMAL);
#endif

    #ifdef GL_CLAMP_TO_EDGE
NODE_DEFINE_CONSTANT(target, GL_CLAMP_TO_EDGE);
#endif

    #ifdef GL_MAX_ELEMENTS_VERTICES
NODE_DEFINE_CONSTANT(target, GL_MAX_ELEMENTS_VERTICES);
#endif

    #ifdef GL_MAX_ELEMENTS_INDICES
NODE_DEFINE_CONSTANT(target, GL_MAX_ELEMENTS_INDICES);
#endif

    #ifdef GL_BGR
NODE_DEFINE_CONSTANT(target, GL_BGR);
#endif

    #ifdef GL_BGRA
NODE_DEFINE_CONSTANT(target, GL_BGRA);
#endif

    #ifdef GL_UNSIGNED_BYTE_3_3_2
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_BYTE_3_3_2);
#endif

    #ifdef GL_UNSIGNED_BYTE_2_3_3_REV
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_BYTE_2_3_3_REV);
#endif

    #ifdef GL_UNSIGNED_SHORT_5_6_5
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT_5_6_5);
#endif

    #ifdef GL_UNSIGNED_SHORT_5_6_5_REV
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT_5_6_5_REV);
#endif

    #ifdef GL_UNSIGNED_SHORT_4_4_4_4
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT_4_4_4_4);
#endif

    #ifdef GL_UNSIGNED_SHORT_4_4_4_4_REV
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT_4_4_4_4_REV);
#endif

    #ifdef GL_UNSIGNED_SHORT_5_5_5_1
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT_5_5_5_1);
#endif

    #ifdef GL_UNSIGNED_SHORT_1_5_5_5_REV
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT_1_5_5_5_REV);
#endif

    #ifdef GL_UNSIGNED_INT_8_8_8_8
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_INT_8_8_8_8);
#endif

    #ifdef GL_UNSIGNED_INT_8_8_8_8_REV
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_INT_8_8_8_8_REV);
#endif

    #ifdef GL_UNSIGNED_INT_10_10_10_2
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_INT_10_10_10_2);
#endif

    #ifdef GL_UNSIGNED_INT_2_10_10_10_REV
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_INT_2_10_10_10_REV);
#endif

    #ifdef GL_LIGHT_MODEL_COLOR_CONTROL
NODE_DEFINE_CONSTANT(target, GL_LIGHT_MODEL_COLOR_CONTROL);
#endif

    #ifdef GL_SINGLE_COLOR
NODE_DEFINE_CONSTANT(target, GL_SINGLE_COLOR);
#endif

    #ifdef GL_SEPARATE_SPECULAR_COLOR
NODE_DEFINE_CONSTANT(target, GL_SEPARATE_SPECULAR_COLOR);
#endif

    #ifdef GL_TEXTURE_MIN_LOD
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_MIN_LOD);
#endif

    #ifdef GL_TEXTURE_MAX_LOD
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_MAX_LOD);
#endif

    #ifdef GL_TEXTURE_BASE_LEVEL
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BASE_LEVEL);
#endif

    #ifdef GL_TEXTURE_MAX_LEVEL
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_MAX_LEVEL);
#endif

    #ifdef GL_SMOOTH_POINT_SIZE_RANGE
NODE_DEFINE_CONSTANT(target, GL_SMOOTH_POINT_SIZE_RANGE);
#endif

    #ifdef GL_SMOOTH_POINT_SIZE_GRANULARITY
NODE_DEFINE_CONSTANT(target, GL_SMOOTH_POINT_SIZE_GRANULARITY);
#endif

    #ifdef GL_SMOOTH_LINE_WIDTH_RANGE
NODE_DEFINE_CONSTANT(target, GL_SMOOTH_LINE_WIDTH_RANGE);
#endif

    #ifdef GL_SMOOTH_LINE_WIDTH_GRANULARITY
NODE_DEFINE_CONSTANT(target, GL_SMOOTH_LINE_WIDTH_GRANULARITY);
#endif

    #ifdef GL_ALIASED_POINT_SIZE_RANGE
NODE_DEFINE_CONSTANT(target, GL_ALIASED_POINT_SIZE_RANGE);
#endif

    #ifdef GL_ALIASED_LINE_WIDTH_RANGE
NODE_DEFINE_CONSTANT(target, GL_ALIASED_LINE_WIDTH_RANGE);
#endif

    #ifdef GL_PACK_SKIP_IMAGES
NODE_DEFINE_CONSTANT(target, GL_PACK_SKIP_IMAGES);
#endif

    #ifdef GL_PACK_IMAGE_HEIGHT
NODE_DEFINE_CONSTANT(target, GL_PACK_IMAGE_HEIGHT);
#endif

    #ifdef GL_UNPACK_SKIP_IMAGES
NODE_DEFINE_CONSTANT(target, GL_UNPACK_SKIP_IMAGES);
#endif

    #ifdef GL_UNPACK_IMAGE_HEIGHT
NODE_DEFINE_CONSTANT(target, GL_UNPACK_IMAGE_HEIGHT);
#endif

    #ifdef GL_TEXTURE_3D
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_3D);
#endif

    #ifdef GL_PROXY_TEXTURE_3D
NODE_DEFINE_CONSTANT(target, GL_PROXY_TEXTURE_3D);
#endif

    #ifdef GL_TEXTURE_DEPTH
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_DEPTH);
#endif

    #ifdef GL_TEXTURE_WRAP_R
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_WRAP_R);
#endif

    #ifdef GL_MAX_3D_TEXTURE_SIZE
NODE_DEFINE_CONSTANT(target, GL_MAX_3D_TEXTURE_SIZE);
#endif

    #ifdef GL_TEXTURE_BINDING_3D
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BINDING_3D);
#endif

    #ifdef GL_CONSTANT_COLOR
NODE_DEFINE_CONSTANT(target, GL_CONSTANT_COLOR);
#endif

    #ifdef GL_ONE_MINUS_CONSTANT_COLOR
NODE_DEFINE_CONSTANT(target, GL_ONE_MINUS_CONSTANT_COLOR);
#endif

    #ifdef GL_CONSTANT_ALPHA
NODE_DEFINE_CONSTANT(target, GL_CONSTANT_ALPHA);
#endif

    #ifdef GL_ONE_MINUS_CONSTANT_ALPHA
NODE_DEFINE_CONSTANT(target, GL_ONE_MINUS_CONSTANT_ALPHA);
#endif

    #ifdef GL_COLOR_TABLE
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE);
#endif

    #ifdef GL_POST_CONVOLUTION_COLOR_TABLE
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_COLOR_TABLE);
#endif

    #ifdef GL_POST_COLOR_MATRIX_COLOR_TABLE
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_COLOR_TABLE);
#endif

    #ifdef GL_PROXY_COLOR_TABLE
NODE_DEFINE_CONSTANT(target, GL_PROXY_COLOR_TABLE);
#endif

    #ifdef GL_PROXY_POST_CONVOLUTION_COLOR_TABLE
NODE_DEFINE_CONSTANT(target, GL_PROXY_POST_CONVOLUTION_COLOR_TABLE);
#endif

    #ifdef GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE
NODE_DEFINE_CONSTANT(target, GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE);
#endif

    #ifdef GL_COLOR_TABLE_SCALE
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_SCALE);
#endif

    #ifdef GL_COLOR_TABLE_BIAS
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_BIAS);
#endif

    #ifdef GL_COLOR_TABLE_FORMAT
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_FORMAT);
#endif

    #ifdef GL_COLOR_TABLE_WIDTH
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_WIDTH);
#endif

    #ifdef GL_COLOR_TABLE_RED_SIZE
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_RED_SIZE);
#endif

    #ifdef GL_COLOR_TABLE_GREEN_SIZE
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_GREEN_SIZE);
#endif

    #ifdef GL_COLOR_TABLE_BLUE_SIZE
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_BLUE_SIZE);
#endif

    #ifdef GL_COLOR_TABLE_ALPHA_SIZE
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_ALPHA_SIZE);
#endif

    #ifdef GL_COLOR_TABLE_LUMINANCE_SIZE
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_LUMINANCE_SIZE);
#endif

    #ifdef GL_COLOR_TABLE_INTENSITY_SIZE
NODE_DEFINE_CONSTANT(target, GL_COLOR_TABLE_INTENSITY_SIZE);
#endif

    #ifdef GL_CONVOLUTION_1D
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_1D);
#endif

    #ifdef GL_CONVOLUTION_2D
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_2D);
#endif

    #ifdef GL_SEPARABLE_2D
NODE_DEFINE_CONSTANT(target, GL_SEPARABLE_2D);
#endif

    #ifdef GL_CONVOLUTION_BORDER_MODE
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_BORDER_MODE);
#endif

    #ifdef GL_CONVOLUTION_FILTER_SCALE
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_FILTER_SCALE);
#endif

    #ifdef GL_CONVOLUTION_FILTER_BIAS
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_FILTER_BIAS);
#endif

    #ifdef GL_REDUCE
NODE_DEFINE_CONSTANT(target, GL_REDUCE);
#endif

    #ifdef GL_CONVOLUTION_FORMAT
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_FORMAT);
#endif

    #ifdef GL_CONVOLUTION_WIDTH
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_WIDTH);
#endif

    #ifdef GL_CONVOLUTION_HEIGHT
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_HEIGHT);
#endif

    #ifdef GL_MAX_CONVOLUTION_WIDTH
NODE_DEFINE_CONSTANT(target, GL_MAX_CONVOLUTION_WIDTH);
#endif

    #ifdef GL_MAX_CONVOLUTION_HEIGHT
NODE_DEFINE_CONSTANT(target, GL_MAX_CONVOLUTION_HEIGHT);
#endif

    #ifdef GL_POST_CONVOLUTION_RED_SCALE
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_RED_SCALE);
#endif

    #ifdef GL_POST_CONVOLUTION_GREEN_SCALE
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_GREEN_SCALE);
#endif

    #ifdef GL_POST_CONVOLUTION_BLUE_SCALE
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_BLUE_SCALE);
#endif

    #ifdef GL_POST_CONVOLUTION_ALPHA_SCALE
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_ALPHA_SCALE);
#endif

    #ifdef GL_POST_CONVOLUTION_RED_BIAS
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_RED_BIAS);
#endif

    #ifdef GL_POST_CONVOLUTION_GREEN_BIAS
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_GREEN_BIAS);
#endif

    #ifdef GL_POST_CONVOLUTION_BLUE_BIAS
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_BLUE_BIAS);
#endif

    #ifdef GL_POST_CONVOLUTION_ALPHA_BIAS
NODE_DEFINE_CONSTANT(target, GL_POST_CONVOLUTION_ALPHA_BIAS);
#endif

    #ifdef GL_CONSTANT_BORDER
NODE_DEFINE_CONSTANT(target, GL_CONSTANT_BORDER);
#endif

    #ifdef GL_REPLICATE_BORDER
NODE_DEFINE_CONSTANT(target, GL_REPLICATE_BORDER);
#endif

    #ifdef GL_CONVOLUTION_BORDER_COLOR
NODE_DEFINE_CONSTANT(target, GL_CONVOLUTION_BORDER_COLOR);
#endif

    #ifdef GL_COLOR_MATRIX
NODE_DEFINE_CONSTANT(target, GL_COLOR_MATRIX);
#endif

    #ifdef GL_COLOR_MATRIX_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_COLOR_MATRIX_STACK_DEPTH);
#endif

    #ifdef GL_MAX_COLOR_MATRIX_STACK_DEPTH
NODE_DEFINE_CONSTANT(target, GL_MAX_COLOR_MATRIX_STACK_DEPTH);
#endif

    #ifdef GL_POST_COLOR_MATRIX_RED_SCALE
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_RED_SCALE);
#endif

    #ifdef GL_POST_COLOR_MATRIX_GREEN_SCALE
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_GREEN_SCALE);
#endif

    #ifdef GL_POST_COLOR_MATRIX_BLUE_SCALE
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_BLUE_SCALE);
#endif

    #ifdef GL_POST_COLOR_MATRIX_ALPHA_SCALE
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_ALPHA_SCALE);
#endif

    #ifdef GL_POST_COLOR_MATRIX_RED_BIAS
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_RED_BIAS);
#endif

    #ifdef GL_POST_COLOR_MATRIX_GREEN_BIAS
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_GREEN_BIAS);
#endif

    #ifdef GL_POST_COLOR_MATRIX_BLUE_BIAS
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_BLUE_BIAS);
#endif

    #ifdef GL_POST_COLOR_MATRIX_ALPHA_BIAS
NODE_DEFINE_CONSTANT(target, GL_POST_COLOR_MATRIX_ALPHA_BIAS);
#endif

    #ifdef GL_HISTOGRAM
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM);
#endif

    #ifdef GL_PROXY_HISTOGRAM
NODE_DEFINE_CONSTANT(target, GL_PROXY_HISTOGRAM);
#endif

    #ifdef GL_HISTOGRAM_WIDTH
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM_WIDTH);
#endif

    #ifdef GL_HISTOGRAM_FORMAT
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM_FORMAT);
#endif

    #ifdef GL_HISTOGRAM_RED_SIZE
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM_RED_SIZE);
#endif

    #ifdef GL_HISTOGRAM_GREEN_SIZE
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM_GREEN_SIZE);
#endif

    #ifdef GL_HISTOGRAM_BLUE_SIZE
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM_BLUE_SIZE);
#endif

    #ifdef GL_HISTOGRAM_ALPHA_SIZE
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM_ALPHA_SIZE);
#endif

    #ifdef GL_HISTOGRAM_LUMINANCE_SIZE
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM_LUMINANCE_SIZE);
#endif

    #ifdef GL_HISTOGRAM_SINK
NODE_DEFINE_CONSTANT(target, GL_HISTOGRAM_SINK);
#endif

    #ifdef GL_MINMAX
NODE_DEFINE_CONSTANT(target, GL_MINMAX);
#endif

    #ifdef GL_MINMAX_FORMAT
NODE_DEFINE_CONSTANT(target, GL_MINMAX_FORMAT);
#endif

    #ifdef GL_MINMAX_SINK
NODE_DEFINE_CONSTANT(target, GL_MINMAX_SINK);
#endif

    #ifdef GL_TABLE_TOO_LARGE
NODE_DEFINE_CONSTANT(target, GL_TABLE_TOO_LARGE);
#endif

    #ifdef GL_BLEND_EQUATION
NODE_DEFINE_CONSTANT(target, GL_BLEND_EQUATION);
#endif

    #ifdef GL_MIN
NODE_DEFINE_CONSTANT(target, GL_MIN);
#endif

    #ifdef GL_MAX
NODE_DEFINE_CONSTANT(target, GL_MAX);
#endif

    #ifdef GL_FUNC_ADD
NODE_DEFINE_CONSTANT(target, GL_FUNC_ADD);
#endif

    #ifdef GL_FUNC_SUBTRACT
NODE_DEFINE_CONSTANT(target, GL_FUNC_SUBTRACT);
#endif

    #ifdef GL_FUNC_REVERSE_SUBTRACT
NODE_DEFINE_CONSTANT(target, GL_FUNC_REVERSE_SUBTRACT);
#endif

    #ifdef GL_BLEND_COLOR
NODE_DEFINE_CONSTANT(target, GL_BLEND_COLOR);
#endif

    #ifdef GL_TEXTURE0
NODE_DEFINE_CONSTANT(target, GL_TEXTURE0);
#endif

    #ifdef GL_TEXTURE1
NODE_DEFINE_CONSTANT(target, GL_TEXTURE1);
#endif

    #ifdef GL_TEXTURE2
NODE_DEFINE_CONSTANT(target, GL_TEXTURE2);
#endif

    #ifdef GL_TEXTURE3
NODE_DEFINE_CONSTANT(target, GL_TEXTURE3);
#endif

    #ifdef GL_TEXTURE4
NODE_DEFINE_CONSTANT(target, GL_TEXTURE4);
#endif

    #ifdef GL_TEXTURE5
NODE_DEFINE_CONSTANT(target, GL_TEXTURE5);
#endif

    #ifdef GL_TEXTURE6
NODE_DEFINE_CONSTANT(target, GL_TEXTURE6);
#endif

    #ifdef GL_TEXTURE7
NODE_DEFINE_CONSTANT(target, GL_TEXTURE7);
#endif

    #ifdef GL_TEXTURE8
NODE_DEFINE_CONSTANT(target, GL_TEXTURE8);
#endif

    #ifdef GL_TEXTURE9
NODE_DEFINE_CONSTANT(target, GL_TEXTURE9);
#endif

    #ifdef GL_TEXTURE10
NODE_DEFINE_CONSTANT(target, GL_TEXTURE10);
#endif

    #ifdef GL_TEXTURE11
NODE_DEFINE_CONSTANT(target, GL_TEXTURE11);
#endif

    #ifdef GL_TEXTURE12
NODE_DEFINE_CONSTANT(target, GL_TEXTURE12);
#endif

    #ifdef GL_TEXTURE13
NODE_DEFINE_CONSTANT(target, GL_TEXTURE13);
#endif

    #ifdef GL_TEXTURE14
NODE_DEFINE_CONSTANT(target, GL_TEXTURE14);
#endif

    #ifdef GL_TEXTURE15
NODE_DEFINE_CONSTANT(target, GL_TEXTURE15);
#endif

    #ifdef GL_TEXTURE16
NODE_DEFINE_CONSTANT(target, GL_TEXTURE16);
#endif

    #ifdef GL_TEXTURE17
NODE_DEFINE_CONSTANT(target, GL_TEXTURE17);
#endif

    #ifdef GL_TEXTURE18
NODE_DEFINE_CONSTANT(target, GL_TEXTURE18);
#endif

    #ifdef GL_TEXTURE19
NODE_DEFINE_CONSTANT(target, GL_TEXTURE19);
#endif

    #ifdef GL_TEXTURE20
NODE_DEFINE_CONSTANT(target, GL_TEXTURE20);
#endif

    #ifdef GL_TEXTURE21
NODE_DEFINE_CONSTANT(target, GL_TEXTURE21);
#endif

    #ifdef GL_TEXTURE22
NODE_DEFINE_CONSTANT(target, GL_TEXTURE22);
#endif

    #ifdef GL_TEXTURE23
NODE_DEFINE_CONSTANT(target, GL_TEXTURE23);
#endif

    #ifdef GL_TEXTURE24
NODE_DEFINE_CONSTANT(target, GL_TEXTURE24);
#endif

    #ifdef GL_TEXTURE25
NODE_DEFINE_CONSTANT(target, GL_TEXTURE25);
#endif

    #ifdef GL_TEXTURE26
NODE_DEFINE_CONSTANT(target, GL_TEXTURE26);
#endif

    #ifdef GL_TEXTURE27
NODE_DEFINE_CONSTANT(target, GL_TEXTURE27);
#endif

    #ifdef GL_TEXTURE28
NODE_DEFINE_CONSTANT(target, GL_TEXTURE28);
#endif

    #ifdef GL_TEXTURE29
NODE_DEFINE_CONSTANT(target, GL_TEXTURE29);
#endif

    #ifdef GL_TEXTURE30
NODE_DEFINE_CONSTANT(target, GL_TEXTURE30);
#endif

    #ifdef GL_TEXTURE31
NODE_DEFINE_CONSTANT(target, GL_TEXTURE31);
#endif

    #ifdef GL_ACTIVE_TEXTURE
NODE_DEFINE_CONSTANT(target, GL_ACTIVE_TEXTURE);
#endif

    #ifdef GL_CLIENT_ACTIVE_TEXTURE
NODE_DEFINE_CONSTANT(target, GL_CLIENT_ACTIVE_TEXTURE);
#endif

    #ifdef GL_MAX_TEXTURE_UNITS
NODE_DEFINE_CONSTANT(target, GL_MAX_TEXTURE_UNITS);
#endif

    #ifdef GL_NORMAL_MAP
NODE_DEFINE_CONSTANT(target, GL_NORMAL_MAP);
#endif

    #ifdef GL_REFLECTION_MAP
NODE_DEFINE_CONSTANT(target, GL_REFLECTION_MAP);
#endif

    #ifdef GL_TEXTURE_CUBE_MAP
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_CUBE_MAP);
#endif

    #ifdef GL_TEXTURE_BINDING_CUBE_MAP
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BINDING_CUBE_MAP);
#endif

    #ifdef GL_TEXTURE_CUBE_MAP_POSITIVE_X
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_CUBE_MAP_POSITIVE_X);
#endif

    #ifdef GL_TEXTURE_CUBE_MAP_NEGATIVE_X
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_CUBE_MAP_NEGATIVE_X);
#endif

    #ifdef GL_TEXTURE_CUBE_MAP_POSITIVE_Y
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_CUBE_MAP_POSITIVE_Y);
#endif

    #ifdef GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_CUBE_MAP_NEGATIVE_Y);
#endif

    #ifdef GL_TEXTURE_CUBE_MAP_POSITIVE_Z
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_CUBE_MAP_POSITIVE_Z);
#endif

    #ifdef GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_CUBE_MAP_NEGATIVE_Z);
#endif

    #ifdef GL_PROXY_TEXTURE_CUBE_MAP
NODE_DEFINE_CONSTANT(target, GL_PROXY_TEXTURE_CUBE_MAP);
#endif

    #ifdef GL_MAX_CUBE_MAP_TEXTURE_SIZE
NODE_DEFINE_CONSTANT(target, GL_MAX_CUBE_MAP_TEXTURE_SIZE);
#endif

    #ifdef GL_COMPRESSED_ALPHA
NODE_DEFINE_CONSTANT(target, GL_COMPRESSED_ALPHA);
#endif

    #ifdef GL_COMPRESSED_LUMINANCE
NODE_DEFINE_CONSTANT(target, GL_COMPRESSED_LUMINANCE);
#endif

    #ifdef GL_COMPRESSED_LUMINANCE_ALPHA
NODE_DEFINE_CONSTANT(target, GL_COMPRESSED_LUMINANCE_ALPHA);
#endif

    #ifdef GL_COMPRESSED_INTENSITY
NODE_DEFINE_CONSTANT(target, GL_COMPRESSED_INTENSITY);
#endif

    #ifdef GL_COMPRESSED_RGB
NODE_DEFINE_CONSTANT(target, GL_COMPRESSED_RGB);
#endif

    #ifdef GL_COMPRESSED_RGBA
NODE_DEFINE_CONSTANT(target, GL_COMPRESSED_RGBA);
#endif

    #ifdef GL_TEXTURE_COMPRESSION_HINT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COMPRESSION_HINT);
#endif

    #ifdef GL_TEXTURE_COMPRESSED_IMAGE_SIZE
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COMPRESSED_IMAGE_SIZE);
#endif

    #ifdef GL_TEXTURE_COMPRESSED
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_COMPRESSED);
#endif

    #ifdef GL_NUM_COMPRESSED_TEXTURE_FORMATS
NODE_DEFINE_CONSTANT(target, GL_NUM_COMPRESSED_TEXTURE_FORMATS);
#endif

    #ifdef GL_COMPRESSED_TEXTURE_FORMATS
NODE_DEFINE_CONSTANT(target, GL_COMPRESSED_TEXTURE_FORMATS);
#endif

    #ifdef GL_MULTISAMPLE
NODE_DEFINE_CONSTANT(target, GL_MULTISAMPLE);
#endif

    #ifdef GL_SAMPLE_ALPHA_TO_COVERAGE
NODE_DEFINE_CONSTANT(target, GL_SAMPLE_ALPHA_TO_COVERAGE);
#endif

    #ifdef GL_SAMPLE_ALPHA_TO_ONE
NODE_DEFINE_CONSTANT(target, GL_SAMPLE_ALPHA_TO_ONE);
#endif

    #ifdef GL_SAMPLE_COVERAGE
NODE_DEFINE_CONSTANT(target, GL_SAMPLE_COVERAGE);
#endif

    #ifdef GL_SAMPLE_BUFFERS
NODE_DEFINE_CONSTANT(target, GL_SAMPLE_BUFFERS);
#endif

    #ifdef GL_SAMPLES
NODE_DEFINE_CONSTANT(target, GL_SAMPLES);
#endif

    #ifdef GL_SAMPLE_COVERAGE_VALUE
NODE_DEFINE_CONSTANT(target, GL_SAMPLE_COVERAGE_VALUE);
#endif

    #ifdef GL_SAMPLE_COVERAGE_INVERT
NODE_DEFINE_CONSTANT(target, GL_SAMPLE_COVERAGE_INVERT);
#endif

    #ifdef GL_MULTISAMPLE_BIT
NODE_DEFINE_CONSTANT(target, GL_MULTISAMPLE_BIT);
#endif

    #ifdef GL_TRANSPOSE_MODELVIEW_MATRIX
NODE_DEFINE_CONSTANT(target, GL_TRANSPOSE_MODELVIEW_MATRIX);
#endif

    #ifdef GL_TRANSPOSE_PROJECTION_MATRIX
NODE_DEFINE_CONSTANT(target, GL_TRANSPOSE_PROJECTION_MATRIX);
#endif

    #ifdef GL_TRANSPOSE_TEXTURE_MATRIX
NODE_DEFINE_CONSTANT(target, GL_TRANSPOSE_TEXTURE_MATRIX);
#endif

    #ifdef GL_TRANSPOSE_COLOR_MATRIX
NODE_DEFINE_CONSTANT(target, GL_TRANSPOSE_COLOR_MATRIX);
#endif

    #ifdef GL_COMBINE
NODE_DEFINE_CONSTANT(target, GL_COMBINE);
#endif

    #ifdef GL_COMBINE_RGB
NODE_DEFINE_CONSTANT(target, GL_COMBINE_RGB);
#endif

    #ifdef GL_COMBINE_ALPHA
NODE_DEFINE_CONSTANT(target, GL_COMBINE_ALPHA);
#endif

    #ifdef GL_SOURCE0_RGB
NODE_DEFINE_CONSTANT(target, GL_SOURCE0_RGB);
#endif

    #ifdef GL_SOURCE1_RGB
NODE_DEFINE_CONSTANT(target, GL_SOURCE1_RGB);
#endif

    #ifdef GL_SOURCE2_RGB
NODE_DEFINE_CONSTANT(target, GL_SOURCE2_RGB);
#endif

    #ifdef GL_SOURCE0_ALPHA
NODE_DEFINE_CONSTANT(target, GL_SOURCE0_ALPHA);
#endif

    #ifdef GL_SOURCE1_ALPHA
NODE_DEFINE_CONSTANT(target, GL_SOURCE1_ALPHA);
#endif

    #ifdef GL_SOURCE2_ALPHA
NODE_DEFINE_CONSTANT(target, GL_SOURCE2_ALPHA);
#endif

    #ifdef GL_OPERAND0_RGB
NODE_DEFINE_CONSTANT(target, GL_OPERAND0_RGB);
#endif

    #ifdef GL_OPERAND1_RGB
NODE_DEFINE_CONSTANT(target, GL_OPERAND1_RGB);
#endif

    #ifdef GL_OPERAND2_RGB
NODE_DEFINE_CONSTANT(target, GL_OPERAND2_RGB);
#endif

    #ifdef GL_OPERAND0_ALPHA
NODE_DEFINE_CONSTANT(target, GL_OPERAND0_ALPHA);
#endif

    #ifdef GL_OPERAND1_ALPHA
NODE_DEFINE_CONSTANT(target, GL_OPERAND1_ALPHA);
#endif

    #ifdef GL_OPERAND2_ALPHA
NODE_DEFINE_CONSTANT(target, GL_OPERAND2_ALPHA);
#endif

    #ifdef GL_RGB_SCALE
NODE_DEFINE_CONSTANT(target, GL_RGB_SCALE);
#endif

    #ifdef GL_ADD_SIGNED
NODE_DEFINE_CONSTANT(target, GL_ADD_SIGNED);
#endif

    #ifdef GL_INTERPOLATE
NODE_DEFINE_CONSTANT(target, GL_INTERPOLATE);
#endif

    #ifdef GL_SUBTRACT
NODE_DEFINE_CONSTANT(target, GL_SUBTRACT);
#endif

    #ifdef GL_CONSTANT
NODE_DEFINE_CONSTANT(target, GL_CONSTANT);
#endif

    #ifdef GL_PRIMARY_COLOR
NODE_DEFINE_CONSTANT(target, GL_PRIMARY_COLOR);
#endif

    #ifdef GL_PREVIOUS
NODE_DEFINE_CONSTANT(target, GL_PREVIOUS);
#endif

    #ifdef GL_DOT3_RGB
NODE_DEFINE_CONSTANT(target, GL_DOT3_RGB);
#endif

    #ifdef GL_DOT3_RGBA
NODE_DEFINE_CONSTANT(target, GL_DOT3_RGBA);
#endif

    #ifdef GL_CLAMP_TO_BORDER
NODE_DEFINE_CONSTANT(target, GL_CLAMP_TO_BORDER);
#endif

    #ifdef GL_ARB_multitexture
NODE_DEFINE_CONSTANT(target, GL_ARB_multitexture);
#endif

    #ifdef GL_TEXTURE0_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE0_ARB);
#endif

    #ifdef GL_TEXTURE1_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE1_ARB);
#endif

    #ifdef GL_TEXTURE2_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE2_ARB);
#endif

    #ifdef GL_TEXTURE3_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE3_ARB);
#endif

    #ifdef GL_TEXTURE4_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE4_ARB);
#endif

    #ifdef GL_TEXTURE5_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE5_ARB);
#endif

    #ifdef GL_TEXTURE6_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE6_ARB);
#endif

    #ifdef GL_TEXTURE7_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE7_ARB);
#endif

    #ifdef GL_TEXTURE8_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE8_ARB);
#endif

    #ifdef GL_TEXTURE9_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE9_ARB);
#endif

    #ifdef GL_TEXTURE10_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE10_ARB);
#endif

    #ifdef GL_TEXTURE11_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE11_ARB);
#endif

    #ifdef GL_TEXTURE12_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE12_ARB);
#endif

    #ifdef GL_TEXTURE13_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE13_ARB);
#endif

    #ifdef GL_TEXTURE14_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE14_ARB);
#endif

    #ifdef GL_TEXTURE15_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE15_ARB);
#endif

    #ifdef GL_TEXTURE16_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE16_ARB);
#endif

    #ifdef GL_TEXTURE17_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE17_ARB);
#endif

    #ifdef GL_TEXTURE18_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE18_ARB);
#endif

    #ifdef GL_TEXTURE19_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE19_ARB);
#endif

    #ifdef GL_TEXTURE20_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE20_ARB);
#endif

    #ifdef GL_TEXTURE21_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE21_ARB);
#endif

    #ifdef GL_TEXTURE22_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE22_ARB);
#endif

    #ifdef GL_TEXTURE23_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE23_ARB);
#endif

    #ifdef GL_TEXTURE24_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE24_ARB);
#endif

    #ifdef GL_TEXTURE25_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE25_ARB);
#endif

    #ifdef GL_TEXTURE26_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE26_ARB);
#endif

    #ifdef GL_TEXTURE27_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE27_ARB);
#endif

    #ifdef GL_TEXTURE28_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE28_ARB);
#endif

    #ifdef GL_TEXTURE29_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE29_ARB);
#endif

    #ifdef GL_TEXTURE30_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE30_ARB);
#endif

    #ifdef GL_TEXTURE31_ARB
NODE_DEFINE_CONSTANT(target, GL_TEXTURE31_ARB);
#endif

    #ifdef GL_ACTIVE_TEXTURE_ARB
NODE_DEFINE_CONSTANT(target, GL_ACTIVE_TEXTURE_ARB);
#endif

    #ifdef GL_CLIENT_ACTIVE_TEXTURE_ARB
NODE_DEFINE_CONSTANT(target, GL_CLIENT_ACTIVE_TEXTURE_ARB);
#endif

    #ifdef GL_MAX_TEXTURE_UNITS_ARB
NODE_DEFINE_CONSTANT(target, GL_MAX_TEXTURE_UNITS_ARB);
#endif

    #ifdef GL_MESA_shader_debug
NODE_DEFINE_CONSTANT(target, GL_MESA_shader_debug);
#endif

    #ifdef GL_DEBUG_OBJECT_MESA
NODE_DEFINE_CONSTANT(target, GL_DEBUG_OBJECT_MESA);
#endif

    #ifdef GL_DEBUG_PRINT_MESA
NODE_DEFINE_CONSTANT(target, GL_DEBUG_PRINT_MESA);
#endif

    #ifdef GL_DEBUG_ASSERT_MESA
NODE_DEFINE_CONSTANT(target, GL_DEBUG_ASSERT_MESA);
#endif

    #ifdef GL_MESA_packed_depth_stencil
NODE_DEFINE_CONSTANT(target, GL_MESA_packed_depth_stencil);
#endif

    #ifdef GL_DEPTH_STENCIL_MESA
NODE_DEFINE_CONSTANT(target, GL_DEPTH_STENCIL_MESA);
#endif

    #ifdef GL_UNSIGNED_INT_24_8_MESA
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_INT_24_8_MESA);
#endif

    #ifdef GL_UNSIGNED_INT_8_24_REV_MESA
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_INT_8_24_REV_MESA);
#endif

    #ifdef GL_UNSIGNED_SHORT_15_1_MESA
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT_15_1_MESA);
#endif

    #ifdef GL_UNSIGNED_SHORT_1_15_REV_MESA
NODE_DEFINE_CONSTANT(target, GL_UNSIGNED_SHORT_1_15_REV_MESA);
#endif

    #ifdef GL_MESA_program_debug
NODE_DEFINE_CONSTANT(target, GL_MESA_program_debug);
#endif

    #ifdef GL_FRAGMENT_PROGRAM_POSITION_MESA
NODE_DEFINE_CONSTANT(target, GL_FRAGMENT_PROGRAM_POSITION_MESA);
#endif

    #ifdef GL_FRAGMENT_PROGRAM_CALLBACK_MESA
NODE_DEFINE_CONSTANT(target, GL_FRAGMENT_PROGRAM_CALLBACK_MESA);
#endif

    #ifdef GL_FRAGMENT_PROGRAM_CALLBACK_FUNC_MESA
NODE_DEFINE_CONSTANT(target, GL_FRAGMENT_PROGRAM_CALLBACK_FUNC_MESA);
#endif

    #ifdef GL_FRAGMENT_PROGRAM_CALLBACK_DATA_MESA
NODE_DEFINE_CONSTANT(target, GL_FRAGMENT_PROGRAM_CALLBACK_DATA_MESA);
#endif

    #ifdef GL_VERTEX_PROGRAM_POSITION_MESA
NODE_DEFINE_CONSTANT(target, GL_VERTEX_PROGRAM_POSITION_MESA);
#endif

    #ifdef GL_VERTEX_PROGRAM_CALLBACK_MESA
NODE_DEFINE_CONSTANT(target, GL_VERTEX_PROGRAM_CALLBACK_MESA);
#endif

    #ifdef GL_VERTEX_PROGRAM_CALLBACK_FUNC_MESA
NODE_DEFINE_CONSTANT(target, GL_VERTEX_PROGRAM_CALLBACK_FUNC_MESA);
#endif

    #ifdef GL_VERTEX_PROGRAM_CALLBACK_DATA_MESA
NODE_DEFINE_CONSTANT(target, GL_VERTEX_PROGRAM_CALLBACK_DATA_MESA);
#endif

    #ifdef GL_MESA_texture_array
NODE_DEFINE_CONSTANT(target, GL_MESA_texture_array);
#endif

    #ifdef GL_TEXTURE_1D_ARRAY_EXT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_1D_ARRAY_EXT);
#endif

    #ifdef GL_PROXY_TEXTURE_1D_ARRAY_EXT
NODE_DEFINE_CONSTANT(target, GL_PROXY_TEXTURE_1D_ARRAY_EXT);
#endif

    #ifdef GL_TEXTURE_2D_ARRAY_EXT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_2D_ARRAY_EXT);
#endif

    #ifdef GL_PROXY_TEXTURE_2D_ARRAY_EXT
NODE_DEFINE_CONSTANT(target, GL_PROXY_TEXTURE_2D_ARRAY_EXT);
#endif

    #ifdef GL_TEXTURE_BINDING_1D_ARRAY_EXT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BINDING_1D_ARRAY_EXT);
#endif

    #ifdef GL_TEXTURE_BINDING_2D_ARRAY_EXT
NODE_DEFINE_CONSTANT(target, GL_TEXTURE_BINDING_2D_ARRAY_EXT);
#endif

    #ifdef GL_MAX_ARRAY_TEXTURE_LAYERS_EXT
NODE_DEFINE_CONSTANT(target, GL_MAX_ARRAY_TEXTURE_LAYERS_EXT);
#endif

    #ifdef GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT
NODE_DEFINE_CONSTANT(target, GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT);
#endif

    #ifdef GL_ATI_blend_equation_separate
NODE_DEFINE_CONSTANT(target, GL_ATI_blend_equation_separate);
#endif

    #ifdef GL_ALPHA_BLEND_EQUATION_ATI
NODE_DEFINE_CONSTANT(target, GL_ALPHA_BLEND_EQUATION_ATI);
#endif

    #ifdef GL_OES_EGL_image
NODE_DEFINE_CONSTANT(target, GL_OES_EGL_image);
#endif

   
  }
}  // namespace node
